config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'sessions'}
  

  get 'buying_requests/filter' => 'buying_requests#filter', as: "buying_requests_filter"
  resources :buying_requests

  root 'welcome#index'

  get "/contacts/new" => 'welcome#new_contact'
  post "/contacts" => 'welcome#create_contact'
  get 'faq' => 'welcome#faq'
  get 'terms-conditions' => 'welcome#terms_and_conditions'
  get 'about' => 'welcome#about_us'
  get 'why-us' => 'welcome#why_us'
  get 'user-agreement' => 'welcome#user_agreement'
  get 'our-services' => 'welcome#our_services'
  get 'how-we-work' => 'welcome#how_we_work'
  get 'our-policy' => 'welcome#our_policy'
  get 'good-to-know' => 'welcome#good_to_know'
  get 'country-frequency' => 'welcome#country_frequency'
  post 'send-equipment-enquiry' => 'welcome#create_equipment_enquiry'
  get 'equipment_details/:id' => 'equipments#equipment_details', as: "equipment_details"
  get 'listings' => 'equipments#index'
  get 'listings/filter' => 'equipments#filter', as: "listing_filter"
  get 'add_favourite' => 'equipments#add_favourite'
  get 'remove_favourite' => 'equipments#remove_favourite'

  authenticate :user do
    namespace :seller do
      get 'dashboard' => 'dashboard#index'
      resources :profile, only: [:edit, :update]
      resources :buying_requests
      resources :buying_proposals, only: [:index, :new, :create, :show]
      get 'request_for_more_info' => 'buying_requests#request_for_more_info', as: :request_for_more_info
      post 'send_request_for_more_info' => 'buying_requests#send_request_for_more_info', as: :send_request_for_more_info
      
      get 'my_buying_request_list' => 'buying_requests#my_buying_request_list', as: :my_buying_request_list
      get 'my_buying_request/:id' => 'buying_requests#my_buying_request_show', as: :my_buying_request
      
      get 'received_proposals' => 'buying_proposals#received_proposals', as: :received_proposals
      get 'received_proposal/:id' => 'buying_proposals#received_proposals_show', as: :received_proposal
      
      get 'listings/filter' => 'equipment#filter', as: "listing_filter"
      resources :equipment
      get 'fetch_categories' => 'equipment#categories'
      get 'fetch_categories_by_category_type' => 'equipment#categories_by_category_type'
      resources "equipment-enquiries", only: [:index, :show, :destroy], :controller => :equipment_enquiries, :as => :equipment_enquiries do
        collection do
          get 'unread'
        end
      end
      get 'questions' => 'equipment_enquiries#questions', as: "questions"
      get 'question/:id' => 'equipment_enquiries#show_question', as: "question"
      delete 'question/:id' => 'equipment_enquiries#destroy'
      get 'offers' => 'equipment_enquiries#offers', as: "offers"
      get 'offer/:id' => 'equipment_enquiries#show_offer', as: "offer"
      delete 'offer/:id' => 'equipment_enquiries#destroy'
      put 'respond_to_offer/:id' => 'equipment_enquiries#respond_to_offer', as: "respond_to_offer"
      post 'reply_to_question/:id' => 'equipment_enquiries#reply_to_question', as: "reply_to_question"
      resources :messages, only: [:show, :new, :create] do
        collection do
          get 'inbox'
          get 'sentbox'
          get 'autocomplete'
          post 'remove'
          get 'unread'
        end
        member do
          post :reply
          post :trash
          post :untrash
        end
      end
      
      get 'orders' => 'order#index', as: "orders"
      get 'orders/:id' => 'order#show', as: "order"
      get 'invoices' => 'order#invoices', as: "invoices"
      put 'order_update/:id' => 'order#update', as: "orders_update"
      get 'update_shipping/:id' => 'order#update_shipping', as: "update_shipping"
      post 'save_shipping/:id' => 'order#save_shipping', as: "save_shipping"
      get 'order_invoice/:id' => 'order#download_invoice', as: "order_invoice"
      get 'favourites' => 'equipment#favourites', as: "favourites"
      delete 'remove_favourite/:id' => 'equipment#remove_favourite', as: "remove_favourite"
      get 'add_preference' => 'equipment#add_preference'
      get 'remove_preference' => 'equipment#remove_preference'
      get 'ask_for_services' => 'dashboard#ask_for_services'
      get 'available_for_preview' => 'equipment#available_for_preview'

      get 'inquiry-center' => 'inquiry_center#index', as: 'inquiry_center' 
      get 'inquiry-center/detail/:id' => 'inquiry_center#detail', as: 'detail_inquiry_center' 
      post 'delete-inquiry' => 'inquiry_center#delete_inquiry', as: 'delete_inquiry' 
      post 'mark-unread-inquiry' => 'inquiry_center#mark_unread_inquiry', as: 'mark_unread_inquiry' 
      post 'reject-inquiry' => 'inquiry_center#reject_inquiry', as: 'reject_inquiry' 
      post 'report-spam-inquiry' => 'inquiry_center#report_spam_inquiry', as: 'report_spam_inquiry' 
      post 'add-user-contact' => 'inquiry_center#add_user_contact', as: 'add_user_contact' 
      post 'save_shipping_inquiry/:id' => 'inquiry_center#save_shipping_inquiry', as: "save_shipping_inquiry"
      put 'inquiry_update_contact/:id' => 'inquiry_center#inquiry_update_contact', as: "inquiry_update_contact"
      put 'make-offer/:id' => 'inquiry_center#make_offer', as: "make_offer"
      
    end
        
  end

  namespace :admin do
    get 'accept_request' => 'buying_requests#accept_request'
    get 'accept_proposal' => 'buying_requests#accept_proposal'
    get 'accept_info_request' => 'buying_requests#accept_info_request'
    get 'edit_and_accept_info_request' => 'buying_requests#edit_and_accept_info_request'
    put 'update_and_accept_info_request' => 'buying_requests#update_and_accept_info_request'
    get 'edit_and_accept_proposal' => 'buying_requests#edit_and_accept_proposal'
    put 'update_and_accept_proposal' => 'buying_requests#update_and_accept_proposal'

    get 'approve_enquiry_request' => 'equipment_enquiries#approve_enquiry'
    post 'send_reply/:id' => 'contact_requests#send_reply', as: :create_reply
    get 'download_proposal_attachemnt' => 'buying_proposals#download'
    get 'edit_page_content' => 'page_content_managements#edit_page_content'
    post 'save_page_content' => 'page_content_managements#save_page_content'
  end
end

app/controllers/buying_requests_controller.rb
class BuyingRequestsController < ApplicationController
	before_action :find_associated_data, only: [:index, :filter, :edit]
		
	def index
		@buying_requests = BuyingRequest.approved.order("created_at DESC").search(params[:q]).page(params[:page])
		
		@page_content_data = PageContentManagement.where(:page_url => "buying_requests")
		@content_data = {}
		@page_content_data.each do |v|		
			@content_data[v.page_section] = v.content		
		end
		
	end

	def filter
	
		@page_content_data = PageContentManagement.where(:page_url => "buying_requests")
		@content_data = {}
		@page_content_data.each do |v|		
			@content_data[v.page_section] = v.content		
		end
	
		condition = []
		if params[:filter]
			attributes = filter_params
			attributes.delete_if {|k,v| v.blank?}
			attributes.each do |attribute, value|
				condition << "#{attribute.to_s} = ?"
			end
		end
		if condition.length > 0
			@buying_requests = BuyingRequest.where([condition.join(' AND '), *attributes.values]).approved.order('id').page params[:page]
		else
			@buying_requests = BuyingRequest.order("created_at DESC").approved.page params[:page]
		end
		render :index
	end

	def new
		@buying_request = BuyingRequest.new
		@buying_request.images.build
		
		@page_content_data = PageContentManagement.where(:page_url => "post_buying_requests")
		@content_data = {}
		@page_content_data.each do |v|		
			@content_data[v.page_section] = v.content		
		end
		
	end
	
	def create
	
		if params[:buying_request][:images_attributes].present?
			params[:buying_request][:images_attributes].each do |index,img|
				unless params[:buying_request][:images_attributes][index][:image].present?
					params[:buying_request][:images_attributes][index][:image] = params[:buying_request][:images_attributes][index][:image_cache]
				end
			end
		end

    @tmp_images = {}
    temp_image_attributes = {}

    new_params = buying_request_params
    
		@buying_request = BuyingRequest.new(buying_request_params)
		if @buying_request.valid?
			if new_params[:brand_id] == "0"
	      if params[:other][:manufacturer_name].present?
	        manufacturer = Manufacturer.find_or_create_by(:name => params[:other][:manufacturer_name], :status => 1)
	        new_params[:brand_id] = manufacturer.id
	      else
	        new_params.delete(:brand_id)
	      end
	    end
	   
	    if new_params[:category_id] == "0"
	    	if new_params[:category_name].present?
	    		new_params.delete(:category_id)
	    	end
	    end
	    
      @buying_request = BuyingRequest.new(new_params)
		end
		@buying_request.status = "New"

    if buying_request_params[:images_attributes].present?
      index = 0
      buying_request_params[:images_attributes].each do |key,value|
        next if value[:_destroy]=="1"
        temp_image_attributes[index.to_s] = value
        index += 1
      end
      temp_image_attributes.each do |key, value|
        if value[:tmp_image].present? && value[:_destroy]=="false" && !value[:image].present?
          @tmp_images[key] = value[:tmp_image]
        end
      end
    end
     
		if @buying_request.save
			@tmp_images.each do |key, tmp_image|
			img_path = Rails.root.to_s + '/public' + tmp_image
			if File.exists?(img_path)
			  buying_request_image = @buying_request.images.new
			  buying_request_image.image = File.open(img_path , 'rb')
			  buying_request_image.save
			end
		end
			redirect_to new_buying_request_path, notice: 'Successfully Created'
		else
		
      @tmp_images.each do |key, tmp_image|
        img_path = Rails.root.to_s + '/public' + tmp_image
        if File.exists?(img_path)
          buying_request_image = @buying_request.images.new
          buying_request_image.image = File.open(img_path , 'rb')
        end
      end
      @buying_request.images.build if (@buying_request.images.count==0 && index < 4)
      
		@page_content_data = PageContentManagement.where(:page_url => "post_buying_requests")
		@content_data = {}
		@page_content_data.each do |v|		
			@content_data[v.page_section] = v.content		
		end
      
      render 'new'
		end
	end
	
	def edit
		@buying_request = BuyingRequest.find(params[:id])
		
		@page_content_data = PageContentManagement.where(:page_url => "post_buying_requests")
		@content_data = {}
		@page_content_data.each do |v|		
			@content_data[v.page_section] = v.content		
		end
		
		render 'new'
	end
	
	def update
	
		@buying_request = BuyingRequest.find(params[:id])
				
		if params[:buying_request][:images_attributes].present?
		  params[:buying_request][:images_attributes].each do |index,img|
			unless params[:buying_request][:images_attributes][index][:image].present?
			  params[:buying_request][:images_attributes][index][:image] = params[:buying_request][:images_attributes][index][:image_cache]
			end
		  end
		end

		@tmp_images = {}
		temp_image_attributes = {}

		new_params = buying_request_params
		
		@buying_request.assign_attributes( new_params.except(:images_attributes) )
		
		if @buying_request.valid?
			if new_params[:brand_id] == "0"
			  if params[:other][:manufacturer_name].present?
				manufacturer = Manufacturer.find_or_create_by(:name => params[:other][:manufacturer_name], :status => 1)
				new_params[:brand_id] = manufacturer.id
			  else
				new_params.delete(:brand_id)
			  end
			end
			if new_params[:category_id] == "0"
				if new_params[:category_name].present?
					new_params.delete(:category_id)
				end
			end
		end

		if buying_request_params[:images_attributes].present?
		  index = 0
		  buying_request_params[:images_attributes].each do |key,value|
			next if value[:_destroy]=="1"
			temp_image_attributes[index.to_s] = value
			index += 1
		  end
		  temp_image_attributes.each do |key, value|
			if value[:tmp_image].present? && value[:_destroy]=="false" && !value[:image].present?
			  @tmp_images[key] = value[:tmp_image]
			end
		  end
		end
		
		if @buying_request.update(new_params)
			@tmp_images.each do |key, tmp_image|
				img_path = Rails.root.to_s + '/public' + tmp_image
				if File.exists?(img_path)
				  buying_request_image = @buying_request.images.new
				  buying_request_image.image = File.open(img_path , 'rb')
				  buying_request_image.save
				end
			end
			redirect_to seller_my_buying_request_list_path, notice: 'Successfully Updated'
		else
		  @tmp_images.each do |key, tmp_image|
			img_path = Rails.root.to_s + '/public' + tmp_image
			if File.exists?(img_path)
			  buying_request_image = @buying_request.images.new
			  buying_request_image.image = File.open(img_path , 'rb')
			end
		  end
		  @buying_request.images.build if (@buying_request.images.count==0 && index < 4)
		  
			@page_content_data = PageContentManagement.where(:page_url => "post_buying_requests")
			@content_data = {}
			@page_content_data.each do |v|		
				@content_data[v.page_section] = v.content		
			end
		  
		  render 'new'
		end
	end

	private
	def buying_request_params
		params.require(:buying_request).permit(:user_id, :title, :origin, :city, :end_user, :location_id, :brand_id, :category_id, :lead_type, :condition, :expiration_date, :attachment, :image, :description, :name, :email, :mobile, :country_id, :company_name, :company_website, :address, :image_cache, :attachment_cache, :category_name, :images_attributes => [:id,:image,:imageable_id,:imageable_type, :_destroy,:tmp_image,:image_cache])
	end

	def filter_params
		params.require(:filter).permit(:brand_id, :category_id, :lead_type)
	end

	def find_associated_data
		@manufacturers = Manufacturer.active.joins(:equipments).distinct
		@categories = Category.active.all
	end
end

app/controllers/seller/base_controller.rb
class Seller::BaseController < ApplicationController
	#layout 'seller'
	layout 'user'
	before_filter :authenticate_user!
end

app/controllers/seller/buying_proposals_controller.rb
class Seller::BuyingProposalsController < Seller::BaseController
	
	def index
		@proposals = current_user.buying_proposals.includes(:buying_request).order('created_at desc').page(params[:page])
	end

	def new
		if current_user.present?
			@buying_request  = BuyingRequest.approved.where("expiration_date >= ?", Date.today).find(params[:buying_request_id])
			@buying_proposal = BuyingProposal.new
			@image = @buying_proposal.build_image
		else
			redirect_to root_url
		end
	end

	def create
		@buying_proposal = BuyingProposal.new(buying_proposal_params)
		if @buying_proposal.save
			flash[:notice] = "Proposal sent successfully."
			redirect_to seller_buying_requests_path
		else
			@buying_request  = BuyingRequest.approved.where("expiration_date >= ?", Date.today).find(buying_proposal_params[:buying_request_id])
			render :new
		end
	end

	def show
		@buying_proposal = current_user.buying_proposals.find(params[:id])
		rescue ActiveRecord::RecordNotFound
      flash[:error] = "Proposal not found."
      redirect_to seller_buying_proposals_path
	end
	
	def received_proposals
		@proposals = BuyingProposal.joins(:buying_request).where('(buying_requests.user_id = ? OR buying_requests.email = ?)', current_user, current_user.email).order('created_at desc').page(params[:page])
		render :index
	end
	
	def received_proposals_show
		
		if current_user.present?			
			@buying_proposal = BuyingProposal.joins(:buying_request).where('(buying_requests.user_id = ? OR buying_requests.email = ?)', current_user, current_user.email).first
						
			if !@buying_proposal 
				flash[:error] = "Invalid Access !"
				redirect_to seller_received_proposals_path
			else
				render :show
			end	
		else
			redirect_to root_url
		end
	end

	private
	def buying_proposal_params
		params.require(:buying_proposal).permit(:user_id, :proposal, :price, :delivery_time, :currency_id, :buying_request_id, :status, :attachment,:attachment_cache, image_attributes: [:id, :image, :imageable_id, :imageable_type])
	end
end

app/helpers/buying_requests_helper.rb
module BuyingRequestsHelper
end

app/helpers/seller/buying_proposals_helper.rb
module Seller::BuyingProposalsHelper
	def time_diff_in_natural_language(from_time, to_time)
	  from_time = from_time.to_time if from_time.respond_to?(:to_time)
	  to_time = to_time.to_time if to_time.respond_to?(:to_time)
	  distance_in_seconds = ((to_time - from_time).abs).round
	  components = []

	  %w(year month week day).each do |interval|
	    # For each interval type, if the amount of time remaining is greater than
	    # one unit, calculate how many units fit into the remaining time.
	    if distance_in_seconds >= 1.send(interval)
	      delta = (distance_in_seconds / 1.send(interval)).floor
	      distance_in_seconds -= delta.send(interval)
	      components << pluralize(delta, interval)
	    end
	  end

	  components.join(", ")
	end
end

app/helpers/seller/buying_requests_helper.rb
module Seller::BuyingRequestsHelper
	def sent_info_request?(br)
		return BuyingRequestMoreDetail.where(buying_request_id: br.id, user_id: current_user.id).present?
	end

	def sent_proposal?(br)
		return current_user.buying_proposals.pluck(:buying_request_id).include?(br.id)
	end
end

app/helpers/seller/equipment_helper.rb
module Seller::EquipmentHelper
end

app/helpers/seller/messages_helper.rb
module Seller::MessagesHelper
end

app/views/seller/buying_requests/index.html.erb
<% if params[:action] == 'my_buying_request_list'  
	title = 'My Buying Request List';
else 
	title = 'Buying Request List';
end %>

<div class="page page-ui-tables page-dashboard">
	
	
	<div class="page-wrap">

	<!-- <div class="row no-margin no-padding">
			
			<div class="col-md-12 no-padding">
				<div class="dash-head clearfix mb20">
					<div class="left">
						<h4 class="mb5 text-light">Welcome to Power Cozmo</h4>
					</div>
				</div>
			</div>
		</div> -->



		<div class="row no-marging">
			<div class="col-md-12">
				<div class="main-box top-margin-15">
					<div class="main-heding no-t-padding">
						<i class="fa fa-list" aria-hidden="true"></i> <p><%= title %></p> 
					</div>


					<div class="panel-body padding0 dashboard-table">
					
					 <% if @buying_requests.present? %>
							<table class="table">
								<thead>
									<tr>
										<th>S.NO.</th>
										<th>Requester Name</th>
										<th>Title</th>
										<th>Type</th>
										<th>Description</th>
										<th>Added Date</th>
										<th>Expire Date</th>
										<th class="text-center">Action</th>
									</tr>
								</thead>
								
								<tbody>
									<% @buying_requests.each do |br| %>
										<tr>
											<td><%= br.identifier%></td>
											<td><%= br.name%></td>
											<td><%= br.title%></td>
											<td><%= br.lead_type%></td>
											<td><%= truncate(br.description, length: 35)%></td>
											<td><%= br.created_at.strftime('%m/%d/%Y')%></td>
											<td><%= br.expiration_date.strftime('%m/%d/%Y')%></td>
											<td class="text-center">
												
												<% if params[:action] == 'my_buying_request_list' %>
													<%= link_to '<span class="ti-eye"></span>'.html_safe, seller_my_buying_request_path(br), title: "View" %>
													
													<%= link_to '<span class="ti-pencil"></span>'.html_safe, edit_buying_request_path(br), title: "Edit" %>
													
													<%= link_to '<i class="fa fa-trash marginL5 redcolor"></i>'.html_safe, seller_buying_request_path(br),method: :delete,data: { confirm: 'Are you sure?' }, title: "Delete" %>
												
												<% else %>
													<%= link_to '<span class="ti-trash redcolor"></span>'.html_safe, seller_buying_request_path(br), title: "Delete" %>
													<% if br.user_id != current_user[:id] && br.email != current_user[:email] %>
														<% if br.expiration_date >= Date.today %>
														  <%= link_to '<span class="ti-info-alt"></span>'.html_safe, seller_request_for_more_info_path(buying_request_id: br.id), title: "Request For Info" %>
														<% end %>
														<% if br.expiration_date >= Date.today %>
														  <%= link_to '<span class="ti-back-right"></span>'.html_safe, new_seller_buying_proposal_path(buying_request_id: br.id), title: "Submit Your Proposal" %>
														<% end %>
													<% end %>
												<% end %>
											</td>				
																					
										</tr>
									<% end %>
								</tbody>
							</table>
							<%= paginate @buying_requests, :theme => 'listing_page_theme' %>
						 <% else %>
							<p class="no-result">No Buying Requests Found</p>
						 <% end %>	
							
							
					 
				</div>
				</div>
			</div>
		</div>
 
		
		 
	</div>
</div>

app/views/seller/buying_requests/new.html.erb
<!-- Inner Banner Start -->
<section class="innerbanner clearfix">
  <div class="container">
    <h2 class="text-center text-uppercase">POST BUYING REQUEST</h2>
  </div>
</section>

<!-- Welcome to Power Cozmo -->
<section class="clearfix innerwrap">
	<div class="container">
		<div class="row">
			<div class="col-md-7 col-sm-12 col-xs-12">
				<div class="clearfix buyingwrap">
					<ul class="nav nav-tabs text-uppercase">
						<li class="active"><a data-toggle="tab" href="#WhatYouWant">What you want</a></li>
						<li><a data-toggle="tab" href="#WhoYouAre" id="WhoYouAreLink">Additional Information</a></li>
					</ul>
					
					<!-- BUYER REQUEST FORM BEGINs -->
					<%= render partial: 'form'%>
					<!-- BUYER REQUEST FORM ENDs -->
						
				</div>
			</div>
		</div>
      
		<!-- <div class="col-md-5 col-sm-12 col-xs-12 ruleswrap">
			<div class="panel panel-default">
				<div class="panel-heading"><img src="images/light-icon.png" alt="Light" class="marginR5"> Rules</div>
					<div class="panel-body">
					
						 <% if @content_data['rules'] %>
							<%= @content_data['rules'].html_safe %>
						<% else %>
							 <ol>
								<li>Your Buying Request should be specific and clear.</li>
								<li>You shall not post the same buying request repeatedly at one time.</li>
								<li>You shall not post any materials that are untrue, inaccurate, unlawful, invalid</li>
								<li>You undertake that you shall not publish any information or conduct any act whatsoever that infringe the rights of any third party, including but not limited to any intellectual property rights, rights of publicity, rights of personality, rights of privacy, and any other rights of third parties not specifically identified in this clause.</li>
								<li>System generated emails will be sent to you to facilitate notifications of Buying Request status and quotation updates pursuant to your request</li>
							</ol>
						<% end %>
					
						
					</div>
				</div>
			</div>
		</div> -->
    </div>
</section>

<!--How we Work start -->
<!-- <section class="clearfix howweworkwrap">
	<div class="container text-center">
		<h2>HOW IT WORK?</h2>
		<ul class="hwitwk-buying">
			<li>
				<div class="sprites hwitwk-ico1 MB20"></div>
				
				<% if @content_data['how_it_work_step1'] %>
					<%= @content_data['how_it_work_step1'].html_safe %>
				<% else %>
					<h4 class="text-uppercase">Step 1</h4>
					<p>First find the plant or the equipment you are interested in on our web site. </p>
				<% end %>
				
			</li>
			<li>
				<div class="sprites hwitwk-ico2 MB20"></div>
				
				<% if @content_data['how_it_work_step2'] %>
					<%= @content_data['how_it_work_step2'].html_safe %>
				<% else %>
					<h4 class="text-uppercase">Step 2</h4>
					<p>Once you get all your questions answered click in "Make an offer button". </p>
				<% end %>
				
			</li>
			<li>
				<div class="sprites hwitwk-ico3 MB20"></div>
				
				<% if @content_data['how_it_work_step3'] %>
					<%= @content_data['how_it_work_step3'].html_safe %>
				<% else %>
					<h4 class="text-uppercase">Step 3</h4>
					<p>When an offer is accepted and the price agreed, a seller/buyer agreement. </p>
				<% end %>
				
			</li>
			<li>
				<div class="sprites hwitwk-ico9 MB20"></div>
				
				<% if @content_data['how_it_work_step4'] %>
					<%= @content_data['how_it_work_step4'].html_safe %>
				<% else %>
					<h4 class="text-uppercase">Step 4</h4>
					<p>While the payment is clearing the bank you will be sent the seller/buyer contract. </p>
				<% end %>
				
			</li>
		</ul>    
	</div>
</section> -->

<%= javascript_include_tag 'seller/bootstrap-filestyle.min'%>
<script type="text/javascript">
	
	$("#nxt-btn").click(function(){
		$("#WhoYouAreLink").trigger( "click" );
		var offset = $('#WhoYouAreLink').offset();
		var scrollto = offset.top - $('.navbar').outerHeight();
		$('html, body').animate({scrollTop:scrollto}, 0);
	});
	
</script>

app/views/seller/buying_requests/request_for_more_info.html.erb
<div class="page page-forms-elements page-dashboard">
	<ol class="breadcrumb breadcrumb-small">
		<li><a href="<%= seller_dashboard_path %>">Home</a></li>
		<li class="active">Request More Information</li>
	</ol>
	
	<div class="page-wrap">
		
		<div class="row">
			<!-- dashboard header -->
			<div class="col-md-12">
				<div class="dash-head clearfix mb20">
					<div class="left">
						<h4 class="mb5 text-light">Request More Information</h4>
					</div>
				</div>
			</div>
		</div> <!-- #end row -->
		
		<!-- row -->
		<div class="row">
			<section class="content new-msg-content">

<!-- user detail form start -->			
<%= form_for @request_for_more_info, url: seller_send_request_for_more_info_path do |f|%>
	 <%= f.hidden_field :status, value: 'New'%>
     <%= f.hidden_field :user_id, value: current_user.id%>
     <%= f.hidden_field :buying_request_id, value: @buying_request.id%>
				
				<div class="col-sm-12 col-md-12">	
					<div class="panel panel-default panel-hovered panel-stacked mb30">
						<div class="panel-body">
							
							<div class="form-group">
								<label class="col-md-12 control-label">To<sup>*</sup></label>
								<div class="col-md-12">
									<%= f.text_field :receiver, value: "info@powercozmo.com", class: 'form-control mailto-row', id: 'mailto', readonly: true %>
								</div>
							</div>
							
							<div class="clearfix"></div>
							
							<div class="form-group mt20">
								<label class="col-md-12 control-label">Subject<sup>*</sup></label>
								<div class="col-md-12">
									<%= f.text_field :subject, value: @buying_request.title, class: 'form-control mailto-row', id: 'subject', readonly: true %>
								</div>
							</div>
							
							<div class="clearfix"></div>
							
							<div class="form-group mt20">
								<label class="col-md-12 control-label">Message<sup>*</sup></label>
								<div class="col-md-12">
									<%= f.bootsy_area :message, class: 'form-control bootsy-height', id: 'message', placeholder: 'Enter Message', editor_options: { html: true } %>
									<%= error_message(@request_for_more_info, :message)%>
								</div>
							</div>
							
							<div class="clearfix"></div>
							
							<div class="form-group mt20">
								<div class="col-md-12">
									<a href="javascript:void(0)">
										<span class="label label-primary attch-btn" id="attach-btn"><i class="fa fa-paperclip"></i> Attachment</span>
										<%= f.file_field :attachment , style: "display:none;", id: "hidden-attach"%>
									</a>
									<span class="max-limit">Max.32MB</span> </div>
								</div>
							</div>
							
							<div class="clearfix mt20 right">
								<a href="<%= seller_buying_requests_path%>" class="btn btn-primary mr5">Back</a>
							   <button type="submit" class="btn btn-success mr5" value="Send" name="commit">Send</button>
							</div>
										
						</div>	
					</div>	
				</div>
<% end %>
<!-- user detail form end -->
				
			</section>
		</div>
	</div>
</div>

<script type="text/javascript">
  $( "#attach-btn" ).on( "click", function() {
    $('#hidden-attach').click();
  });
</script>