config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'sessions'}
  

  get 'buying_requests/filter' => 'buying_requests#filter', as: "buying_requests_filter"
  resources :buying_requests

  root 'welcome#index'

  get "/contacts/new" => 'welcome#new_contact'
  post "/contacts" => 'welcome#create_contact'
  get 'faq' => 'welcome#faq'
  get 'terms-conditions' => 'welcome#terms_and_conditions'
  get 'about' => 'welcome#about_us'
  get 'why-us' => 'welcome#why_us'
  get 'user-agreement' => 'welcome#user_agreement'
  get 'our-services' => 'welcome#our_services'
  get 'how-we-work' => 'welcome#how_we_work'
  get 'our-policy' => 'welcome#our_policy'
  get 'good-to-know' => 'welcome#good_to_know'
  get 'country-frequency' => 'welcome#country_frequency'
  post 'send-equipment-enquiry' => 'welcome#create_equipment_enquiry'
  get 'equipment_details/:id' => 'equipments#equipment_details', as: "equipment_details"
  get 'listings' => 'equipments#index'
  get 'listings/filter' => 'equipments#filter', as: "listing_filter"
  get 'add_favourite' => 'equipments#add_favourite'
  get 'remove_favourite' => 'equipments#remove_favourite'

  authenticate :user do
    namespace :seller do
      get 'dashboard' => 'dashboard#index'
      resources :profile, only: [:edit, :update]
      resources :buying_requests
      resources :buying_proposals, only: [:index, :new, :create, :show]
      get 'request_for_more_info' => 'buying_requests#request_for_more_info', as: :request_for_more_info
      post 'send_request_for_more_info' => 'buying_requests#send_request_for_more_info', as: :send_request_for_more_info
      
      get 'my_buying_request_list' => 'buying_requests#my_buying_request_list', as: :my_buying_request_list
      get 'my_buying_request/:id' => 'buying_requests#my_buying_request_show', as: :my_buying_request
      
      get 'received_proposals' => 'buying_proposals#received_proposals', as: :received_proposals
      get 'received_proposal/:id' => 'buying_proposals#received_proposals_show', as: :received_proposal
      
      get 'listings/filter' => 'equipment#filter', as: "listing_filter"
      resources :equipment
      get 'fetch_categories' => 'equipment#categories'
      get 'fetch_categories_by_category_type' => 'equipment#categories_by_category_type'
      resources "equipment-enquiries", only: [:index, :show, :destroy], :controller => :equipment_enquiries, :as => :equipment_enquiries do
        collection do
          get 'unread'
        end
      end
      get 'questions' => 'equipment_enquiries#questions', as: "questions"
      get 'question/:id' => 'equipment_enquiries#show_question', as: "question"
      delete 'question/:id' => 'equipment_enquiries#destroy'
      get 'offers' => 'equipment_enquiries#offers', as: "offers"
      get 'offer/:id' => 'equipment_enquiries#show_offer', as: "offer"
      delete 'offer/:id' => 'equipment_enquiries#destroy'
      put 'respond_to_offer/:id' => 'equipment_enquiries#respond_to_offer', as: "respond_to_offer"
      post 'reply_to_question/:id' => 'equipment_enquiries#reply_to_question', as: "reply_to_question"
      resources :messages, only: [:show, :new, :create] do
        collection do
          get 'inbox'
          get 'sentbox'
          get 'autocomplete'
          post 'remove'
          get 'unread'
        end
        member do
          post :reply
          post :trash
          post :untrash
        end
      end
      
      get 'orders' => 'order#index', as: "orders"
      get 'orders/:id' => 'order#show', as: "order"
      get 'invoices' => 'order#invoices', as: "invoices"
      put 'order_update/:id' => 'order#update', as: "orders_update"
      get 'update_shipping/:id' => 'order#update_shipping', as: "update_shipping"
      post 'save_shipping/:id' => 'order#save_shipping', as: "save_shipping"
      get 'order_invoice/:id' => 'order#download_invoice', as: "order_invoice"
      get 'favourites' => 'equipment#favourites', as: "favourites"
      delete 'remove_favourite/:id' => 'equipment#remove_favourite', as: "remove_favourite"
      get 'add_preference' => 'equipment#add_preference'
      get 'remove_preference' => 'equipment#remove_preference'
      get 'ask_for_services' => 'dashboard#ask_for_services'
      get 'available_for_preview' => 'equipment#available_for_preview'

      get 'inquiry-center' => 'inquiry_center#index', as: 'inquiry_center' 
      get 'inquiry-center/detail/:id' => 'inquiry_center#detail', as: 'detail_inquiry_center' 
      post 'delete-inquiry' => 'inquiry_center#delete_inquiry', as: 'delete_inquiry' 
      post 'mark-unread-inquiry' => 'inquiry_center#mark_unread_inquiry', as: 'mark_unread_inquiry' 
      post 'reject-inquiry' => 'inquiry_center#reject_inquiry', as: 'reject_inquiry' 
      post 'report-spam-inquiry' => 'inquiry_center#report_spam_inquiry', as: 'report_spam_inquiry' 
      post 'add-user-contact' => 'inquiry_center#add_user_contact', as: 'add_user_contact' 
      post 'save_shipping_inquiry/:id' => 'inquiry_center#save_shipping_inquiry', as: "save_shipping_inquiry"
      put 'inquiry_update_contact/:id' => 'inquiry_center#inquiry_update_contact', as: "inquiry_update_contact"
      put 'make-offer/:id' => 'inquiry_center#make_offer', as: "make_offer"
      
    end
        
  end

  namespace :admin do
    get 'accept_request' => 'buying_requests#accept_request'
    get 'accept_proposal' => 'buying_requests#accept_proposal'
    get 'accept_info_request' => 'buying_requests#accept_info_request'
    get 'edit_and_accept_info_request' => 'buying_requests#edit_and_accept_info_request'
    put 'update_and_accept_info_request' => 'buying_requests#update_and_accept_info_request'
    get 'edit_and_accept_proposal' => 'buying_requests#edit_and_accept_proposal'
    put 'update_and_accept_proposal' => 'buying_requests#update_and_accept_proposal'

    get 'approve_enquiry_request' => 'equipment_enquiries#approve_enquiry'
    post 'send_reply/:id' => 'contact_requests#send_reply', as: :create_reply
    get 'download_proposal_attachemnt' => 'buying_proposals#download'
    get 'edit_page_content' => 'page_content_managements#edit_page_content'
    post 'save_page_content' => 'page_content_managements#save_page_content'
  end
end

app/controllers/buying_requests_controller.rb
class BuyingRequestsController < ApplicationController
	before_action :find_associated_data, only: [:index, :filter, :edit]
		
	def index
		@buying_requests = BuyingRequest.approved.order("created_at DESC").search(params[:q]).page(params[:page])
		
		@page_content_data = PageContentManagement.where(:page_url => "buying_requests")
		@content_data = {}
		@page_content_data.each do |v|		
			@content_data[v.page_section] = v.content		
		end
		
	end

	def filter
	
		@page_content_data = PageContentManagement.where(:page_url => "buying_requests")
		@content_data = {}
		@page_content_data.each do |v|		
			@content_data[v.page_section] = v.content		
		end
	
		condition = []
		if params[:filter]
			attributes = filter_params
			attributes.delete_if {|k,v| v.blank?}
			attributes.each do |attribute, value|
				condition << "#{attribute.to_s} = ?"
			end
		end
		if condition.length > 0
			@buying_requests = BuyingRequest.where([condition.join(' AND '), *attributes.values]).approved.order('id').page params[:page]
		else
			@buying_requests = BuyingRequest.order("created_at DESC").approved.page params[:page]
		end
		render :index
	end

	def new
		@buying_request = BuyingRequest.new
		@buying_request.images.build
		
		@page_content_data = PageContentManagement.where(:page_url => "post_buying_requests")
		@content_data = {}
		@page_content_data.each do |v|		
			@content_data[v.page_section] = v.content		
		end
		
	end
	
	def create
	
		if params[:buying_request][:images_attributes].present?
			params[:buying_request][:images_attributes].each do |index,img|
				unless params[:buying_request][:images_attributes][index][:image].present?
					params[:buying_request][:images_attributes][index][:image] = params[:buying_request][:images_attributes][index][:image_cache]
				end
			end
		end

    @tmp_images = {}
    temp_image_attributes = {}

    new_params = buying_request_params
    
		@buying_request = BuyingRequest.new(buying_request_params)
		if @buying_request.valid?
			if new_params[:brand_id] == "0"
	      if params[:other][:manufacturer_name].present?
	        manufacturer = Manufacturer.find_or_create_by(:name => params[:other][:manufacturer_name], :status => 1)
	        new_params[:brand_id] = manufacturer.id
	      else
	        new_params.delete(:brand_id)
	      end
	    end
	   
	    if new_params[:category_id] == "0"
	    	if new_params[:category_name].present?
	    		new_params.delete(:category_id)
	    	end
	    end
	    
      @buying_request = BuyingRequest.new(new_params)
		end
		@buying_request.status = "New"

    if buying_request_params[:images_attributes].present?
      index = 0
      buying_request_params[:images_attributes].each do |key,value|
        next if value[:_destroy]=="1"
        temp_image_attributes[index.to_s] = value
        index += 1
      end
      temp_image_attributes.each do |key, value|
        if value[:tmp_image].present? && value[:_destroy]=="false" && !value[:image].present?
          @tmp_images[key] = value[:tmp_image]
        end
      end
    end
     
		if @buying_request.save
			@tmp_images.each do |key, tmp_image|
			img_path = Rails.root.to_s + '/public' + tmp_image
			if File.exists?(img_path)
			  buying_request_image = @buying_request.images.new
			  buying_request_image.image = File.open(img_path , 'rb')
			  buying_request_image.save
			end
		end
			redirect_to new_buying_request_path, notice: 'Successfully Created'
		else
		
      @tmp_images.each do |key, tmp_image|
        img_path = Rails.root.to_s + '/public' + tmp_image
        if File.exists?(img_path)
          buying_request_image = @buying_request.images.new
          buying_request_image.image = File.open(img_path , 'rb')
        end
      end
      @buying_request.images.build if (@buying_request.images.count==0 && index < 4)
      
		@page_content_data = PageContentManagement.where(:page_url => "post_buying_requests")
		@content_data = {}
		@page_content_data.each do |v|		
			@content_data[v.page_section] = v.content		
		end
      
      render 'new'
		end
	end
	
	def edit
		@buying_request = BuyingRequest.find(params[:id])
		
		@page_content_data = PageContentManagement.where(:page_url => "post_buying_requests")
		@content_data = {}
		@page_content_data.each do |v|		
			@content_data[v.page_section] = v.content		
		end
		
		render 'new'
	end
	
	def update
	
		@buying_request = BuyingRequest.find(params[:id])
				
		if params[:buying_request][:images_attributes].present?
		  params[:buying_request][:images_attributes].each do |index,img|
			unless params[:buying_request][:images_attributes][index][:image].present?
			  params[:buying_request][:images_attributes][index][:image] = params[:buying_request][:images_attributes][index][:image_cache]
			end
		  end
		end

		@tmp_images = {}
		temp_image_attributes = {}

		new_params = buying_request_params
		
		@buying_request.assign_attributes( new_params.except(:images_attributes) )
		
		if @buying_request.valid?
			if new_params[:brand_id] == "0"
			  if params[:other][:manufacturer_name].present?
				manufacturer = Manufacturer.find_or_create_by(:name => params[:other][:manufacturer_name], :status => 1)
				new_params[:brand_id] = manufacturer.id
			  else
				new_params.delete(:brand_id)
			  end
			end
			if new_params[:category_id] == "0"
				if new_params[:category_name].present?
					new_params.delete(:category_id)
				end
			end
		end

		if buying_request_params[:images_attributes].present?
		  index = 0
		  buying_request_params[:images_attributes].each do |key,value|
			next if value[:_destroy]=="1"
			temp_image_attributes[index.to_s] = value
			index += 1
		  end
		  temp_image_attributes.each do |key, value|
			if value[:tmp_image].present? && value[:_destroy]=="false" && !value[:image].present?
			  @tmp_images[key] = value[:tmp_image]
			end
		  end
		end
		
		if @buying_request.update(new_params)
			@tmp_images.each do |key, tmp_image|
				img_path = Rails.root.to_s + '/public' + tmp_image
				if File.exists?(img_path)
				  buying_request_image = @buying_request.images.new
				  buying_request_image.image = File.open(img_path , 'rb')
				  buying_request_image.save
				end
			end
			redirect_to seller_my_buying_request_list_path, notice: 'Successfully Updated'
		else
		  @tmp_images.each do |key, tmp_image|
			img_path = Rails.root.to_s + '/public' + tmp_image
			if File.exists?(img_path)
			  buying_request_image = @buying_request.images.new
			  buying_request_image.image = File.open(img_path , 'rb')
			end
		  end
		  @buying_request.images.build if (@buying_request.images.count==0 && index < 4)
		  
			@page_content_data = PageContentManagement.where(:page_url => "post_buying_requests")
			@content_data = {}
			@page_content_data.each do |v|		
				@content_data[v.page_section] = v.content		
			end
		  
		  render 'new'
		end
	end

	private
	def buying_request_params
		params.require(:buying_request).permit(:user_id, :title, :origin, :city, :end_user, :location_id, :brand_id, :category_id, :lead_type, :condition, :expiration_date, :attachment, :image, :description, :name, :email, :mobile, :country_id, :company_name, :company_website, :address, :image_cache, :attachment_cache, :category_name, :images_attributes => [:id,:image,:imageable_id,:imageable_type, :_destroy,:tmp_image,:image_cache])
	end

	def filter_params
		params.require(:filter).permit(:brand_id, :category_id, :lead_type)
	end

	def find_associated_data
		@manufacturers = Manufacturer.active.joins(:equipments).distinct
		@categories = Category.active.all
	end
end

app/helpers/buying_requests_helper.rb
module BuyingRequestsHelper
end

app/helpers/seller/buying_requests_helper.rb
module Seller::BuyingRequestsHelper
	def sent_info_request?(br)
		return BuyingRequestMoreDetail.where(buying_request_id: br.id, user_id: current_user.id).present?
	end

	def sent_proposal?(br)
		return current_user.buying_proposals.pluck(:buying_request_id).include?(br.id)
	end
end

app/views/buying_requests/index.html.erb
<section class="innerbanner clearfix">
  <div class="container">
    <h2 class="text-center text-uppercase">Buying Request</h2>
  </div>
</section>  
  
  
  <section id="md" class="lst-midd-cnt">
    <div class="wht-bg MB30">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 log-rt-buy log-rt-buy-new">
            <h2 class="page-hd MT20 log-rt-buy-bg">Looking for <span>requests</span></h2>
            
            <% if @content_data['top_section_text'] %>
				<%= @content_data['top_section_text'].html_safe %>
			<% else %>
				 <p>Are you interested in responding to a customer’s Buying request? As a supplier registered on the Power Cozmo, you have access to online tools that make doing so easy and efficient. It's all done through power Cozmo.</p>
				<p>Suppliers can respond to Buying Request post through power Cozmo e-mail or through Seller dashboard. Power Cozmo will give the priority for suppliers who’s verified and registered in out Platform </p>
			<% end %>
                        
          </div>
        </div>
      </div>
    </div>
    <div class="wht-bg">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-12 lst-rt-cnt lst-rt-cnt-new">
           <%= form_tag(buying_requests_filter_path, method: :get) do %>
             <div class="lst-slt-bx MR10 lst-slt-wdt">
                <label>Category</label>
                <%= select_tag "filter[category_id]", options_from_collection_for_select(@categories, "id", "name", params[:filter] ? params[:filter][:category_id] : ""), include_blank: "Select Categories", class: "custom-select" %>
              </div>
              <div class="lst-slt-bx MR10 lst-slt-wdt">
              	<label>Manufacturer</label>
                <%= select_tag "filter[brand_id]", options_from_collection_for_select(@manufacturers, "id", "name", params[:filter] ? params[:filter][:brand_id] : ""),include_blank: "Select Manufacturer",class: " custom-select listing_filter" %>
              </div>
              <div class="lst-slt-bx MR10 lst-slt-wdt">
                  <label>Lead Type </label>
                  <%= select_tag "filter[lead_type]", options_for_select(BuyingRequest::LEAD_TYPES, params[:filter] ? params[:filter][:lead_type] : ""), include_blank: "Select Lead Type", class: "custom-select" %>
              </div>
              <div class="lst-slt-bx MR10 lst-slt-wdt filter-btn">
                <label class="display-none">&nbsp;</label>
              	<a href="javascript:void(0)" id="apply-link">Apply</a>
                <%= submit_tag "", id: "apply-btn", :style => "display: none;"%>
                <% if params[:filter].present? %>
                  <%= link_to 'Clear Filters', buying_requests_filter_path(:filter => params[:filter].except(:category_id, :brand_id, :lead_type)) %>
                <% end %>
              </div>
            <% end %>

           </div>
        </div>
      </div>
      <div class="container">
      	<div class="row">
        	<div class="col-lg-12 MT20">
            <div class="tbllistt-new">
            	<table width="100%" border="0" cellspacing="1" cellpadding="0" class="MB30 tbllist">
                <tr class="tbl-sty">
                  <th width="36%">Title</th>
                  <th width="13%">Type</th>
                  <th width="14%" class="txtctr"> SNo </th>
                  <th width="12%"> Added Date </th>
                  <th width="12%"> Expire Date </th>
                  <th width="12%">More Details</th>
                </tr>
                <tr class="tbllistt-pd">
                  <td colspan="6" height="10"></td>
                </tr>
                <% if @buying_requests.present?  %>
                  <% @buying_requests.each do |br| %>
                    <tr class=" evnrwbg brd">
                      <td><%= br.title %></td>
                      <td><%= br.lead_type%></td>
                      <td align="center"><%= br.identifier %></td>
                      <td><%= br.created_at.strftime('%m/%d/%Y')%></td>
                      <td><%= br.expiration_date.strftime('%m/%d/%Y')%></td>
                      <td>
                        <% unless current_user.present? %>
                          <%= link_to('Read more', new_user_session_path(guest_user: true), class: "btn-lgn") %>
                        <% else %>
                          <%= link_to('Read more', seller_buying_request_path(br), class: "btn-lgn") %>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                <% else %>
                  <tr class="evnrwbg brd">
                    <td colspan="6" align="center">No Result Found</td>
                  </tr>
                <% end %>
              </table>
            </div>
            <%= paginate @buying_requests, :theme => 'listing_page_theme' %>
          </div>
        </div>
      </div>
    </div>
  </section>

  <script type="text/javascript">
    $( "#apply-link" ).click(function() {
      $( "#apply-btn" ).click();
    });
  </script>

app/views/buying_requests/new.html.erb
<!-- Inner Banner Start -->
<section class="innerbanner clearfix">
  <div class="container">
    <h2 class="text-center text-uppercase">POST BUYING REQUEST</h2>
  </div>
</section>

<!-- Welcome to Power Cozmo -->
<section class="clearfix innerwrap">
	<div class="container">
		<div class="row">
			<div class="col-md-7 col-sm-12 col-xs-12">
				<div class="clearfix buyingwrap">
					<ul class="nav nav-tabs text-uppercase">
						<li class="active"><a data-toggle="tab" href="#WhatYouWant">What you want</a></li>
						<li><a data-toggle="tab" href="#WhoYouAre" id="WhoYouAreLink">Who you are</a></li>
					</ul>
					
					<!-- BUYER REQUEST FORM BEGINs -->
					<%= render partial: 'form'%>
					<!-- BUYER REQUEST FORM ENDs -->
						
				</div>
			</div>
		</div>
      
		<div class="col-md-5 col-sm-12 col-xs-12 ruleswrap">
			<div class="panel panel-default">
				<div class="panel-heading"><img src="images/light-icon.png" alt="Light" class="marginR5"> Rules</div>
					<div class="panel-body">
					
						 <% if @content_data['rules'] %>
							<%= @content_data['rules'].html_safe %>
						<% else %>
							 <ol>
								<li>Your Buying Request should be specific and clear.</li>
								<li>You shall not post the same buying request repeatedly at one time.</li>
								<li>You shall not post any materials that are untrue, inaccurate, unlawful, invalid</li>
								<li>You undertake that you shall not publish any information or conduct any act whatsoever that infringe the rights of any third party, including but not limited to any intellectual property rights, rights of publicity, rights of personality, rights of privacy, and any other rights of third parties not specifically identified in this clause.</li>
								<li>System generated emails will be sent to you to facilitate notifications of Buying Request status and quotation updates pursuant to your request</li>
							</ol>
						<% end %>
					
						
					</div>
				</div>
			</div>
		</div>
    </div>
</section>

<!--How we Work start -->
<section class="clearfix howweworkwrap">
	<div class="container text-center">
		<h2>HOW IT WORK?</h2>
		<ul class="hwitwk-buying">
			<li>
				<div class="sprites hwitwk-ico1 MB20"></div>
				
				<% if @content_data['how_it_work_step1'] %>
					<%= @content_data['how_it_work_step1'].html_safe %>
				<% else %>
					<h4 class="text-uppercase">Step 1</h4>
					<p>First find the plant or the equipment you are interested in on our web site. </p>
				<% end %>
				
			</li>
			<li>
				<div class="sprites hwitwk-ico2 MB20"></div>
				
				<% if @content_data['how_it_work_step2'] %>
					<%= @content_data['how_it_work_step2'].html_safe %>
				<% else %>
					<h4 class="text-uppercase">Step 2</h4>
					<p>Once you get all your questions answered click in "Make an offer button". </p>
				<% end %>
				
			</li>
			<li>
				<div class="sprites hwitwk-ico3 MB20"></div>
				
				<% if @content_data['how_it_work_step3'] %>
					<%= @content_data['how_it_work_step3'].html_safe %>
				<% else %>
					<h4 class="text-uppercase">Step 3</h4>
					<p>When an offer is accepted and the price agreed, a seller/buyer agreement. </p>
				<% end %>
				
			</li>
			<li>
				<div class="sprites hwitwk-ico9 MB20"></div>
				
				<% if @content_data['how_it_work_step4'] %>
					<%= @content_data['how_it_work_step4'].html_safe %>
				<% else %>
					<h4 class="text-uppercase">Step 4</h4>
					<p>While the payment is clearing the bank you will be sent the seller/buyer contract. </p>
				<% end %>
				
			</li>
		</ul>    
	</div>
</section>

<%= javascript_include_tag 'bootstrap-filestyle.min'%>
<script type="text/javascript">
	
	$("#nxt-btn").click(function(){
		$("#WhoYouAreLink").trigger( "click" );
		var offset = $('#WhoYouAreLink').offset();
		var scrollto = offset.top - $('.navbar').outerHeight();
		$('html, body').animate({scrollTop:scrollto}, 0);
	});
	
</script>