config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'sessions'}
  

  get 'buying_requests/filter' => 'buying_requests#filter', as: "buying_requests_filter"
  resources :buying_requests

  root 'welcome#index'

  get "/contacts/new" => 'welcome#new_contact'
  post "/contacts" => 'welcome#create_contact'
  get 'faq' => 'welcome#faq'
  get 'terms-conditions' => 'welcome#terms_and_conditions'
  get 'about' => 'welcome#about_us'
  get 'why-us' => 'welcome#why_us'
  get 'user-agreement' => 'welcome#user_agreement'
  get 'our-services' => 'welcome#our_services'
  get 'how-we-work' => 'welcome#how_we_work'
  get 'our-policy' => 'welcome#our_policy'
  get 'good-to-know' => 'welcome#good_to_know'
  get 'country-frequency' => 'welcome#country_frequency'
  post 'send-equipment-enquiry' => 'welcome#create_equipment_enquiry'
  get 'equipment_details/:id' => 'equipments#equipment_details', as: "equipment_details"
  get 'listings' => 'equipments#index'
  get 'listings/filter' => 'equipments#filter', as: "listing_filter"
  get 'add_favourite' => 'equipments#add_favourite'
  get 'remove_favourite' => 'equipments#remove_favourite'

  authenticate :user do
    namespace :seller do
      get 'dashboard' => 'dashboard#index'
      resources :profile, only: [:edit, :update]
      resources :buying_requests
      resources :buying_proposals, only: [:index, :new, :create, :show]
      get 'request_for_more_info' => 'buying_requests#request_for_more_info', as: :request_for_more_info
      post 'send_request_for_more_info' => 'buying_requests#send_request_for_more_info', as: :send_request_for_more_info
      
      get 'my_buying_request_list' => 'buying_requests#my_buying_request_list', as: :my_buying_request_list
      get 'my_buying_request/:id' => 'buying_requests#my_buying_request_show', as: :my_buying_request
      
      get 'received_proposals' => 'buying_proposals#received_proposals', as: :received_proposals
      get 'received_proposal/:id' => 'buying_proposals#received_proposals_show', as: :received_proposal
      
      get 'listings/filter' => 'equipment#filter', as: "listing_filter"
      resources :equipment
      get 'fetch_categories' => 'equipment#categories'
      get 'fetch_categories_by_category_type' => 'equipment#categories_by_category_type'
      resources "equipment-enquiries", only: [:index, :show, :destroy], :controller => :equipment_enquiries, :as => :equipment_enquiries do
        collection do
          get 'unread'
        end
      end
      get 'questions' => 'equipment_enquiries#questions', as: "questions"
      get 'question/:id' => 'equipment_enquiries#show_question', as: "question"
      delete 'question/:id' => 'equipment_enquiries#destroy'
      get 'offers' => 'equipment_enquiries#offers', as: "offers"
      get 'offer/:id' => 'equipment_enquiries#show_offer', as: "offer"
      delete 'offer/:id' => 'equipment_enquiries#destroy'
      put 'respond_to_offer/:id' => 'equipment_enquiries#respond_to_offer', as: "respond_to_offer"
      post 'reply_to_question/:id' => 'equipment_enquiries#reply_to_question', as: "reply_to_question"
      resources :messages, only: [:show, :new, :create] do
        collection do
          get 'inbox'
          get 'sentbox'
          get 'autocomplete'
          post 'remove'
          get 'unread'
        end
        member do
          post :reply
          post :trash
          post :untrash
        end
      end
      
      get 'orders' => 'order#index', as: "orders"
      get 'orders/:id' => 'order#show', as: "order"
      get 'invoices' => 'order#invoices', as: "invoices"
      put 'order_update/:id' => 'order#update', as: "orders_update"
      get 'update_shipping/:id' => 'order#update_shipping', as: "update_shipping"
      post 'save_shipping/:id' => 'order#save_shipping', as: "save_shipping"
      get 'order_invoice/:id' => 'order#download_invoice', as: "order_invoice"
      get 'favourites' => 'equipment#favourites', as: "favourites"
      delete 'remove_favourite/:id' => 'equipment#remove_favourite', as: "remove_favourite"
      get 'add_preference' => 'equipment#add_preference'
      get 'remove_preference' => 'equipment#remove_preference'
      get 'ask_for_services' => 'dashboard#ask_for_services'
      get 'available_for_preview' => 'equipment#available_for_preview'

      get 'inquiry-center' => 'inquiry_center#index', as: 'inquiry_center' 
      get 'inquiry-center/detail/:id' => 'inquiry_center#detail', as: 'detail_inquiry_center' 
      post 'delete-inquiry' => 'inquiry_center#delete_inquiry', as: 'delete_inquiry' 
      post 'mark-unread-inquiry' => 'inquiry_center#mark_unread_inquiry', as: 'mark_unread_inquiry' 
      post 'reject-inquiry' => 'inquiry_center#reject_inquiry', as: 'reject_inquiry' 
      post 'report-spam-inquiry' => 'inquiry_center#report_spam_inquiry', as: 'report_spam_inquiry' 
      post 'add-user-contact' => 'inquiry_center#add_user_contact', as: 'add_user_contact' 
      post 'save_shipping_inquiry/:id' => 'inquiry_center#save_shipping_inquiry', as: "save_shipping_inquiry"
      put 'inquiry_update_contact/:id' => 'inquiry_center#inquiry_update_contact', as: "inquiry_update_contact"
      put 'make-offer/:id' => 'inquiry_center#make_offer', as: "make_offer"
      
    end
        
  end

  namespace :admin do
    get 'accept_request' => 'buying_requests#accept_request'
    get 'accept_proposal' => 'buying_requests#accept_proposal'
    get 'accept_info_request' => 'buying_requests#accept_info_request'
    get 'edit_and_accept_info_request' => 'buying_requests#edit_and_accept_info_request'
    put 'update_and_accept_info_request' => 'buying_requests#update_and_accept_info_request'
    get 'edit_and_accept_proposal' => 'buying_requests#edit_and_accept_proposal'
    put 'update_and_accept_proposal' => 'buying_requests#update_and_accept_proposal'

    get 'approve_enquiry_request' => 'equipment_enquiries#approve_enquiry'
    post 'send_reply/:id' => 'contact_requests#send_reply', as: :create_reply
    get 'download_proposal_attachemnt' => 'buying_proposals#download'
    get 'edit_page_content' => 'page_content_managements#edit_page_content'
    post 'save_page_content' => 'page_content_managements#save_page_content'
  end
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
	before_action :find_associated_data, only: [:index, :filter]
		
	def index
		@equipments = Equipment.not_inactive.order('created_at desc').page params[:page]
		
		@page_content_data = PageContentManagement.where(:page_url => "listings")
		@content_data = {}
		@page_content_data.each do |v|		
			@content_data[v.page_section] = v.content		
		end	
				
	end
	
	def index_solr_backup
	
		@page_content_data = PageContentManagement.where(:page_url => "listings")
		@content_data = {}
		@page_content_data.each do |v|		
			@content_data[v.page_section] = v.content		
		end
	
		#@equipments = Equipment.not_inactive.order('created_at desc').page params[:page]
		search = Equipment.solr_search do 
		
			 #without :status, 0
			 			 
			 paginate :page => params[:page], :per_page => 12
			 order_by :created_at, :desc
		end
		
		@equipments = search.results
		
		#abort(@equipments.to_json)
	end

	def equipment_details
	
		@page_content_data = PageContentManagement.where(:page_url => "equipment_details")
		@content_data = {}
		@page_content_data.each do |v|		
			@content_data[v.page_section] = v.content		
		end
	
		@top_bar_ad = Advertisement.where(:active => 1).find_by_page_reference('listing details top horizontal').try(:image).try(:image).try(:ad_horizontal).try(:url)
		@side_panel_ad = Advertisement.where(:active => 1).find_by_page_reference('listing details right panel').try(:image).try(:image).try(:ad_square).try(:url)
		@equipment = Equipment.not_inactive.includes(:country, :manufacturer, :category, :user).find_by_id(params[:id])
		
		if @equipment
		
			if current_user
				@favorite_data = Favorite.where('favorites.user_id = ? AND favorites.equipment_id = ?', current_user.id, @equipment.id).first
			end 
		
			['sub_sub_category_id', 'sub_category_id', 'category_id'].each do |attribute|
				value = @equipment.send(attribute)
				if value.present?
					@similar_products = Equipment.not_inactive.where("#{attribute.to_sym} = ? AND id != ?", value, @equipment.id)
					if @similar_products.count >= 12
						break
					end
				end
			end
		else
			flash[:notice] = "Equipment not found."
			redirect_to listings_path and return
		end
		@countries = Country.active.all
		respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "power_cozmo_#{@equipment.name}",
        			 :layout => 'listing_detail_pdf.html.erb',
        			 :disposition => 'attachment'
      end
    end
	end
	
	def filter
	
		@page_content_data = PageContentManagement.where(:page_url => "listings")
		@content_data = {}
		@page_content_data.each do |v|		
			@content_data[v.page_section] = v.content		
		end
	
		if params[:q].present?
			@search = Equipment.not_inactive.search(params[:q])
			@search.sorts = 'created_at desc' if @search.sorts.empty?
			@search_result = @search.result
		else
			@search_result = "Equipment".constantize
		end
		condition = []
		if params[:filter]
			attributes = filter_params
			attributes.delete_if {|k,v| v.blank?}
			attributes.each do |attribute, value|
				condition << "#{attribute.to_s} = ?"
			end
		end
		if condition.length > 0
			@equipments = @search_result.not_inactive.where([condition.join(' AND '), *attributes.values]).order('created_at desc').page params[:page]
		else
			@equipments = @search_result.not_inactive.order('created_at desc').page(params[:page])
		end
		render :index
	end

	def filter_solr_backup
		
		@page_content_data = PageContentManagement.where(:page_url => "listings")
		@content_data = {}
		@page_content_data.each do |v|		
			@content_data[v.page_section] = v.content		
		end
	
		search_qry = {}
	
		search = Equipment.solr_search do
			
			#without(:status, 0)
			
			if params[:filter]
				attributes = filter_params
				attributes.delete_if {|k,v| v.blank?}
				attributes.each do |attribute, value|
					with attribute.to_s, value
					
					search_qry[attribute] = value
				end
			end
			
			if params[:q]
				attributes_q = params[:q]
				attributes_q.delete_if {|k,v| v.blank?}
				attributes_q.each do |attribute_q, value_q|
								
					any do
						fulltext value_q, :fields => :name
						fulltext value_q, :fields => :identifier
						fulltext value_q, :fields => :country_name
						fulltext value_q, :fields => :description
						fulltext value_q, :fields => :manufacturer_name
						fulltext value_q, :fields => :category_name
						fulltext value_q, :fields => :sub_category_name
						fulltext value_q, :fields => :sub_sub_category_name
					end
					
					search_qry['search'] = value_q
					
				end
			end
				
			paginate :page => params[:page], :per_page => 12
			order_by :created_at, :desc
		end
			
		
		@equipments = search.results
		
		if current_user
			if !search_qry.empty?
				
				history_data = SearchHistory.where('search_histories.user_id = ? AND search_histories.search = ?', current_user.id, search_qry.to_json).first	
				
				if !history_data		
				
					SearchHistory.create(user_id: current_user.id, search: search_qry.to_json)
				
				end
				
			end
		end
		
		#abort(search_qry.to_json)
		#abort(@equipments.to_json)
		
		render :index
	end
	
	def add_favourite
	
		favorite_data = Favorite.where('favorites.user_id = ? AND favorites.equipment_id = ?', current_user.id, params[:equipment_id]).first
	
		if favorite_data
			render json: {message: 'Already in favourite !', status: '201'}
		else
			Favorite.create(user_id: current_user.id, equipment_id: params[:equipment_id])
			
			render json: {message: 'Equipment successfully added in favourite.', status: '200'}
			
		end
	
	end
	
	def remove_favourite
		Favorite.where(user_id: current_user.id, equipment_id: params[:equipment_id]).delete_all
		render json: {message: 'Equipment successfully removed from favourite.', status: '200'}
	end

	private
		def filter_params
			params.require(:filter).permit(:country_id, :manufacturer_id, :manufacture_year, :manufacturer_id,:category_id, :sub_category_id, :sub_sub_category_id)
		end

		def find_associated_data
			@top_bar_ad = Advertisement.where(:active => 1).find_by_page_reference('listing top horizontal').try(:image).try(:image).try(:ad_horizontal).try(:url)
			@left_panel_ad = Advertisement.where(:active => 1).find_by_page_reference('listing left panel').try(:image).try(:image).try(:ad_square).try(:url)
			@manufacturers = Manufacturer.joins(:equipments).distinct
			@countries = Country.active.joins(:equipments).distinct
			@categories = Category.active.all
			if Equipment.not_inactive.count > 0
				@manufacture_year_range = (Equipment.not_inactive.minimum('manufacture_year')..Equipment.not_inactive.maximum('manufacture_year')).to_a
			else
				@manufacture_year_range = nil
			end
			@recent_posts = Equipment.not_inactive.where("created_at > ? ", 30.days.ago).limit(12).order("created_at DESC")
		end
end

app/controllers/seller/base_controller.rb
class Seller::BaseController < ApplicationController
	#layout 'seller'
	layout 'user'
	before_filter :authenticate_user!
end

app/controllers/seller/buying_proposals_controller.rb
class Seller::BuyingProposalsController < Seller::BaseController
	
	def index
		@proposals = current_user.buying_proposals.includes(:buying_request).order('created_at desc').page(params[:page])
	end

	def new
		if current_user.present?
			@buying_request  = BuyingRequest.approved.where("expiration_date >= ?", Date.today).find(params[:buying_request_id])
			@buying_proposal = BuyingProposal.new
			@image = @buying_proposal.build_image
		else
			redirect_to root_url
		end
	end

	def create
		@buying_proposal = BuyingProposal.new(buying_proposal_params)
		if @buying_proposal.save
			flash[:notice] = "Proposal sent successfully."
			redirect_to seller_buying_requests_path
		else
			@buying_request  = BuyingRequest.approved.where("expiration_date >= ?", Date.today).find(buying_proposal_params[:buying_request_id])
			render :new
		end
	end

	def show
		@buying_proposal = current_user.buying_proposals.find(params[:id])
		rescue ActiveRecord::RecordNotFound
      flash[:error] = "Proposal not found."
      redirect_to seller_buying_proposals_path
	end
	
	def received_proposals
		@proposals = BuyingProposal.joins(:buying_request).where('(buying_requests.user_id = ? OR buying_requests.email = ?)', current_user, current_user.email).order('created_at desc').page(params[:page])
		render :index
	end
	
	def received_proposals_show
		
		if current_user.present?			
			@buying_proposal = BuyingProposal.joins(:buying_request).where('(buying_requests.user_id = ? OR buying_requests.email = ?)', current_user, current_user.email).first
						
			if !@buying_proposal 
				flash[:error] = "Invalid Access !"
				redirect_to seller_received_proposals_path
			else
				render :show
			end	
		else
			redirect_to root_url
		end
	end

	private
	def buying_proposal_params
		params.require(:buying_proposal).permit(:user_id, :proposal, :price, :delivery_time, :currency_id, :buying_request_id, :status, :attachment,:attachment_cache, image_attributes: [:id, :image, :imageable_id, :imageable_type])
	end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/equipments_helper.rb
module EquipmentsHelper
	def get_available_for(expiry_date)
		current_time = Time.now
		difference = expiry_date - current_time
		values = Hash.new
		difference > 0 ? values[:status] = "active" : values[:status] = "closed"
		values[:minutes] = ((difference/60)%60).floor
		values[:hours] = ((difference/(60 * 60))%24).floor
		values[:days] = (difference/(60 * 60 * 24)).floor
		return values
	end
end

app/helpers/seller/buying_proposals_helper.rb
module Seller::BuyingProposalsHelper
	def time_diff_in_natural_language(from_time, to_time)
	  from_time = from_time.to_time if from_time.respond_to?(:to_time)
	  to_time = to_time.to_time if to_time.respond_to?(:to_time)
	  distance_in_seconds = ((to_time - from_time).abs).round
	  components = []

	  %w(year month week day).each do |interval|
	    # For each interval type, if the amount of time remaining is greater than
	    # one unit, calculate how many units fit into the remaining time.
	    if distance_in_seconds >= 1.send(interval)
	      delta = (distance_in_seconds / 1.send(interval)).floor
	      distance_in_seconds -= delta.send(interval)
	      components << pluralize(delta, interval)
	    end
	  end

	  components.join(", ")
	end
end

app/helpers/seller/buying_requests_helper.rb
module Seller::BuyingRequestsHelper
	def sent_info_request?(br)
		return BuyingRequestMoreDetail.where(buying_request_id: br.id, user_id: current_user.id).present?
	end

	def sent_proposal?(br)
		return current_user.buying_proposals.pluck(:buying_request_id).include?(br.id)
	end
end

app/helpers/seller/equipment_helper.rb
module Seller::EquipmentHelper
end

app/helpers/seller/messages_helper.rb
module Seller::MessagesHelper
end

app/views/seller/equipment/_right_section.html.erb
<div class="row">
	<div class="RightPanel clearfix">
		<div class="RightUserTitle">Tips</div>
		<div id="section_tips">
			<% if @content_data['user_guide'] %>
				<%= @content_data['user_guide'].html_safe %>
			<% else %>

				<div class="RightIndent">
					<div class="howwork-title">Product Keywords</div>
					<p>
						Please enter keywords that are similar to the product name or words that buyers might use to search for your product (e.g. different name for same product in English), so as to ensure that your product will appear when buyers use these keywords to search for products.Please note: exactly matching your keywords is a must, singular and plural forms are considered identical keywords.
					</p>
				</div>

				<div class="RightIndent">
					<div class="howwork-title">To maximize your online marketing results and speed up the processing of your website, we wish to ensure the images you upload meet the following standards:</div>
					<p>Image must be sharp, clear and in focus with product details clearly visible.</p>
					<ul>
						<li>Basic specifications: Ask developer to put image standard</li>
						<li>Size: 360 x 360 pixels (12.7 x 12.7cm) or above</li>
						<li>Resolution: 100 dpi or above</li>
						<li>Color mode: RGB (system doesn't accept CMYK color mode)</li>
						<li>Format: JPG (or JPEG)</li>
						<li>Weight/size(Recommend): 40KB - 2MB</li>
					</ul>
				</div>

				<div class="RightIndent">
					<div class="howwork-title">Primary Product Information</div>
					<ul>
						<li>Ensure accurate search results and make your product more attractive</li>
					</ul>
				</div>

				<div class="RightIndent">
					<div class="howwork-title">Benefits of shipping information</div>
					<ul>
						<li>Helps buyers to calculate a product's landed cost to quickly filter out any unsuitable suppliers</li>
		 				<li>Shortens the inquiry process and gets you more meaningful inquiries</li>
					</ul>
				</div>

			<% end %>
		</div>
		<div class="RightIndent">
			<p class="text-right"><a href="javascript:void(0);" id="section_tips_link" class="tips-view-link" data-reference="section_tips" data-view="more">View More</a></p> 	
		</div>
	</div>
</div>

<script type="text/javascript">
	
	$(document).ready(function(){
  		$(".alert").fadeIn();
  		$(".alert").fadeOut(30000);

	  	//js start for auto show hide 
	  	if($( "#section_tips" ).height() <= 450 ){
			$("#section_tips_link").hide();
		}else{
			$("#section_tips").addClass('set-right-section-tips-block');
		}

		$(".tips-view-link").click(function(){
			var view = $(this).attr('data-view');
			var reference = $(this).attr('data-reference');

			if(view == 'more'){
				$(this).attr('data-view', 'less');
				$(this).html('View Less');	
				$("#" + reference).removeClass('set-right-section-tips-block');

				if($( "#" + reference ).height() <= 450 ){
					$(this).hide();
				}

			}else{
				$(this).attr('data-view', 'more');
				$(this).html('View More');
				$("#" + reference).addClass('set-right-section-tips-block');	
			}
		});
		//js end for auto show hide 

	});

</script>

app/views/seller/equipment/available_for_preview.html.erb
<% 
if params[:available_for].present? && params[:available_for] != ''
  date = params[:available_for]
  available_for = DateTime.parse(date).strftime("%Y-%m-%d %H:%M:%S")
  remaining_time = (DateTime.parse(date).to_i) - (DateTime.parse(Time.now.to_s).to_i)
else
  available_for = 0
  remaining_time = 0
end
%>                               

<div class="available_for" data-date="<%= available_for %>" data-total-duration="<%= remaining_time %>"></div>

<script type="text/javascript">
$(".available_for").TimeCircles({
    "animation": "smooth",
    "bg_width": 0.7,
    "fg_width": 0.03,
    "circle_radius_multiplier": 0.57, //a cutsom argument for initialization .
    // custom fuction for duration, deafult is 'auto'
    // to use it, define data-total-duration in the initialzing element
    "total_duration": "Created_to_Expiry",
    //"circle_bg_color": "#F0EDED",
    "circle_bg_color": "#DDDDDD",
      "time": {
        "Days": {
          "text": "Days",
          "color": "#36ace3",
          "show": true
        },
        "Hours": {
          "text": "Hours",
          "color": "#36ace3",
          "show": true
        },
        "Minutes": {
          "text": "Minutes",
          "color": "#36ace3",
          "show": true
        },
        "Seconds": {
          "text": "Seconds",
          "color": "#36ace3",
           "show": false
        }
      }
  });

  $(".available_for").css('border-bottom', '1px solid #e5e5e5');
  $(".available_for").css('padding-bottom', '16px')

</script>

app/views/seller/equipment/edit.html.erb
<div class="page page-forms-elements page-dashboard">
 
	
	<div class="page-wrap clearfix">
		
		<!-- <div class="col-md-9 col-sm-12 col-xs-12 no-padding">
			<div class="row no-margin no-padding">
			
				<div class="col-md-12 no-padding">
					<div class="dash-head clearfix mb20">
						<div class="left">
							<h4 class="mb5 text-light">Welcome to Power Cozmo</h4>
						</div>
					</div>
				</div>
			</div> --> <!-- #end row -->

			<div class="row no-marging">
				<div class="col-md-12">
					<div class="main-box top-margin-15 no-radius">
						<div class="main-heding no-t-padding no-border"><i class="fa fa-list" aria-hidden="true"></i> <p>Edit Equipment</p></div>
					</div>
				</div>
			</div>
			
			<!-- row -->
			<div class="row no-margin">
				<%= render partial: "form" %>
			</div>
		</div>

		<div class="col-md-3 col-sm-12 col-xs-12"> 
			<%= render partial: "right_section" %>
		</div>	

	</div>
</div>

app/views/seller/equipment/index.html.erb
<div class="page page-ui-tables page-dashboard">
 <div class="row no-marging">
			
			<div class="col-md-12 no-padding">
				<div class="dash-head clearfix mt15 mb20 margin-bt">
					
				</div>
			</div>
		</div>
	
	<div class="page-wrap">
		
		 
		
		<!-- row -->
		<div class="row no-marging">
			<!-- Basic Table -->
			<div class="col-md-12">
				<div class="panel panel-lined panel-hovered mb20 table-responsive basic-table">
					
					<div class="main-box">

					<div class="main-heding no-t-padding"><i class="fa fa-list" aria-hidden="true"></i> <p>My Listed Equipments</p> 				
				</div>

					<div class="panel-body padding0 dashboard-table">
					 
						<% if @equipments.present? %>
							<table class="table">
								<thead>
									<tr>
										<th>Identifier</th>
										<th>Name</th>
										<th>Description</th>
										<th class="text-center">Image</th>
										<th>Valid Till</th>
										<th class="text-center">Status</th>
										<th class="text-center">Action</th>
									</tr>
								</thead>
								<tbody>
									<% @equipments.each_with_index do |equipment,index| %>
										<tr>
											<td><%= equipment.identifier %></td>
											<td><%= equipment.name %></td>
											<td><%=truncate(equipment.description, :length => 50) %></td>
											<td class="text-center">
												<% if equipment.images.present? %>
												  <%= image_tag(equipment.images.first.try(:image), width: '50', alt: equipment.name) %>
												<% else %>
												  <i class="fa fa-file-image-o"></i>
												<% end %>
											</td>
											<td><%= equipment.availble_for.strftime("%d-%b-%Y %H:%M") if equipment.availble_for.present? %></td>
											<td class="text-center">
												<label class="label label-<%= ['closed','sold','inactive'].include?(equipment.status.to_s) ? 'danger' : 'success' %>"><%= equipment.status.humanize %></label>
												
											</td>
											<td class="text-center">
												<%= link_to '<span class="ti-pencil"></span>'.html_safe, edit_seller_equipment_path(equipment), title: "Edit Equipment" %>
												<%= link_to '<span class="ti-trash redcolor"></span>'.html_safe, seller_equipment_path(equipment), method: :delete, data: { confirm: 'Are you sure?' }, title: "Delete Equipment" %>
											</td>
																						
										</tr>
									<% end %>
								</tbody>
							</table>
							

							<%= paginate @equipments, :theme => 'listing_page_theme' %>
						 <% else %>
							<p class="no-result">No Equipments Found</p>
						 <% end %>	
						 </div>
						 


					</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/seller/equipment/new.html.erb
<div class="page page-forms-elements page-dashboard">
 
	
	<div class="page-wrap clearfix">
		
		<div class="col-md-9 col-sm-12 col-xs-12 no-padding">
			<!-- <div class="row no-margin no-padding">
				
				<div class="col-md-12 no-padding">
					<div class="dash-head clearfix mb20">
						<div class="left">
							<h4 class="mb5 text-light">Welcome to Power Cozmo</h4>
						</div>
					</div>
				</div>
			</div> --> <!-- #end row -->

			<div class="row no-marging">
				<div class="col-md-12">
					<div class="main-box top-margin-15 no-radius">
						<div class="main-heding no-t-padding no-border"><i class="fa fa-list" aria-hidden="true"></i> <p>Add New Equipment</p></div>
					</div>
				</div>
			</div>
			
			<!-- row -->
			<div class="row no-margin">
				<%= render partial: "form" %>
			</div>
		</div>

		<div class="col-md-3 col-sm-12 col-xs-12"> 

			<%= render partial: "right_section" %>

		</div>	

	</div>
</div>