config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'sessions'}
  

  get 'buying_requests/filter' => 'buying_requests#filter', as: "buying_requests_filter"
  resources :buying_requests

  root 'welcome#index'

  get "/contacts/new" => 'welcome#new_contact'
  post "/contacts" => 'welcome#create_contact'
  get 'faq' => 'welcome#faq'
  get 'terms-conditions' => 'welcome#terms_and_conditions'
  get 'about' => 'welcome#about_us'
  get 'why-us' => 'welcome#why_us'
  get 'user-agreement' => 'welcome#user_agreement'
  get 'our-services' => 'welcome#our_services'
  get 'how-we-work' => 'welcome#how_we_work'
  get 'our-policy' => 'welcome#our_policy'
  get 'good-to-know' => 'welcome#good_to_know'
  get 'country-frequency' => 'welcome#country_frequency'
  post 'send-equipment-enquiry' => 'welcome#create_equipment_enquiry'
  get 'equipment_details/:id' => 'equipments#equipment_details', as: "equipment_details"
  get 'listings' => 'equipments#index'
  get 'listings/filter' => 'equipments#filter', as: "listing_filter"
  get 'add_favourite' => 'equipments#add_favourite'
  get 'remove_favourite' => 'equipments#remove_favourite'

  authenticate :user do
    namespace :seller do
      get 'dashboard' => 'dashboard#index'
      resources :profile, only: [:edit, :update]
      resources :buying_requests
      resources :buying_proposals, only: [:index, :new, :create, :show]
      get 'request_for_more_info' => 'buying_requests#request_for_more_info', as: :request_for_more_info
      post 'send_request_for_more_info' => 'buying_requests#send_request_for_more_info', as: :send_request_for_more_info
      
      get 'my_buying_request_list' => 'buying_requests#my_buying_request_list', as: :my_buying_request_list
      get 'my_buying_request/:id' => 'buying_requests#my_buying_request_show', as: :my_buying_request
      
      get 'received_proposals' => 'buying_proposals#received_proposals', as: :received_proposals
      get 'received_proposal/:id' => 'buying_proposals#received_proposals_show', as: :received_proposal
      
      get 'listings/filter' => 'equipment#filter', as: "listing_filter"
      resources :equipment
      get 'fetch_categories' => 'equipment#categories'
      get 'fetch_categories_by_category_type' => 'equipment#categories_by_category_type'
      resources "equipment-enquiries", only: [:index, :show, :destroy], :controller => :equipment_enquiries, :as => :equipment_enquiries do
        collection do
          get 'unread'
        end
      end
      get 'questions' => 'equipment_enquiries#questions', as: "questions"
      get 'question/:id' => 'equipment_enquiries#show_question', as: "question"
      delete 'question/:id' => 'equipment_enquiries#destroy'
      get 'offers' => 'equipment_enquiries#offers', as: "offers"
      get 'offer/:id' => 'equipment_enquiries#show_offer', as: "offer"
      delete 'offer/:id' => 'equipment_enquiries#destroy'
      put 'respond_to_offer/:id' => 'equipment_enquiries#respond_to_offer', as: "respond_to_offer"
      post 'reply_to_question/:id' => 'equipment_enquiries#reply_to_question', as: "reply_to_question"
      resources :messages, only: [:show, :new, :create] do
        collection do
          get 'inbox'
          get 'sentbox'
          get 'autocomplete'
          post 'remove'
          get 'unread'
        end
        member do
          post :reply
          post :trash
          post :untrash
        end
      end
      
      get 'orders' => 'order#index', as: "orders"
      get 'orders/:id' => 'order#show', as: "order"
      get 'invoices' => 'order#invoices', as: "invoices"
      put 'order_update/:id' => 'order#update', as: "orders_update"
      get 'update_shipping/:id' => 'order#update_shipping', as: "update_shipping"
      post 'save_shipping/:id' => 'order#save_shipping', as: "save_shipping"
      get 'order_invoice/:id' => 'order#download_invoice', as: "order_invoice"
      get 'favourites' => 'equipment#favourites', as: "favourites"
      delete 'remove_favourite/:id' => 'equipment#remove_favourite', as: "remove_favourite"
      get 'add_preference' => 'equipment#add_preference'
      get 'remove_preference' => 'equipment#remove_preference'
      get 'ask_for_services' => 'dashboard#ask_for_services'
      get 'available_for_preview' => 'equipment#available_for_preview'

      get 'inquiry-center' => 'inquiry_center#index', as: 'inquiry_center' 
      get 'inquiry-center/detail/:id' => 'inquiry_center#detail', as: 'detail_inquiry_center' 
      post 'delete-inquiry' => 'inquiry_center#delete_inquiry', as: 'delete_inquiry' 
      post 'mark-unread-inquiry' => 'inquiry_center#mark_unread_inquiry', as: 'mark_unread_inquiry' 
      post 'reject-inquiry' => 'inquiry_center#reject_inquiry', as: 'reject_inquiry' 
      post 'report-spam-inquiry' => 'inquiry_center#report_spam_inquiry', as: 'report_spam_inquiry' 
      post 'add-user-contact' => 'inquiry_center#add_user_contact', as: 'add_user_contact' 
      post 'save_shipping_inquiry/:id' => 'inquiry_center#save_shipping_inquiry', as: "save_shipping_inquiry"
      put 'inquiry_update_contact/:id' => 'inquiry_center#inquiry_update_contact', as: "inquiry_update_contact"
      put 'make-offer/:id' => 'inquiry_center#make_offer', as: "make_offer"
      
    end
        
  end

  namespace :admin do
    get 'accept_request' => 'buying_requests#accept_request'
    get 'accept_proposal' => 'buying_requests#accept_proposal'
    get 'accept_info_request' => 'buying_requests#accept_info_request'
    get 'edit_and_accept_info_request' => 'buying_requests#edit_and_accept_info_request'
    put 'update_and_accept_info_request' => 'buying_requests#update_and_accept_info_request'
    get 'edit_and_accept_proposal' => 'buying_requests#edit_and_accept_proposal'
    put 'update_and_accept_proposal' => 'buying_requests#update_and_accept_proposal'

    get 'approve_enquiry_request' => 'equipment_enquiries#approve_enquiry'
    post 'send_reply/:id' => 'contact_requests#send_reply', as: :create_reply
    get 'download_proposal_attachemnt' => 'buying_proposals#download'
    get 'edit_page_content' => 'page_content_managements#edit_page_content'
    post 'save_page_content' => 'page_content_managements#save_page_content'
  end
end

app/controllers/seller/base_controller.rb
class Seller::BaseController < ApplicationController
	#layout 'seller'
	layout 'user'
	before_filter :authenticate_user!
end

app/controllers/seller/buying_proposals_controller.rb
class Seller::BuyingProposalsController < Seller::BaseController
	
	def index
		@proposals = current_user.buying_proposals.includes(:buying_request).order('created_at desc').page(params[:page])
	end

	def new
		if current_user.present?
			@buying_request  = BuyingRequest.approved.where("expiration_date >= ?", Date.today).find(params[:buying_request_id])
			@buying_proposal = BuyingProposal.new
			@image = @buying_proposal.build_image
		else
			redirect_to root_url
		end
	end

	def create
		@buying_proposal = BuyingProposal.new(buying_proposal_params)
		if @buying_proposal.save
			flash[:notice] = "Proposal sent successfully."
			redirect_to seller_buying_requests_path
		else
			@buying_request  = BuyingRequest.approved.where("expiration_date >= ?", Date.today).find(buying_proposal_params[:buying_request_id])
			render :new
		end
	end

	def show
		@buying_proposal = current_user.buying_proposals.find(params[:id])
		rescue ActiveRecord::RecordNotFound
      flash[:error] = "Proposal not found."
      redirect_to seller_buying_proposals_path
	end
	
	def received_proposals
		@proposals = BuyingProposal.joins(:buying_request).where('(buying_requests.user_id = ? OR buying_requests.email = ?)', current_user, current_user.email).order('created_at desc').page(params[:page])
		render :index
	end
	
	def received_proposals_show
		
		if current_user.present?			
			@buying_proposal = BuyingProposal.joins(:buying_request).where('(buying_requests.user_id = ? OR buying_requests.email = ?)', current_user, current_user.email).first
						
			if !@buying_proposal 
				flash[:error] = "Invalid Access !"
				redirect_to seller_received_proposals_path
			else
				render :show
			end	
		else
			redirect_to root_url
		end
	end

	private
	def buying_proposal_params
		params.require(:buying_proposal).permit(:user_id, :proposal, :price, :delivery_time, :currency_id, :buying_request_id, :status, :attachment,:attachment_cache, image_attributes: [:id, :image, :imageable_id, :imageable_type])
	end
end

app/controllers/seller/dashboard_controller.rb
class Seller::DashboardController < Seller::BaseController
	
	def index
		@equipments = current_user.equipment.all.order('created_at desc').limit(4)

		@buying_requests = BuyingRequest.approved.order("created_at DESC")

		@received_messages = current_user.mailbox.inbox.where.not("#{Mailboxer::Message.table_name}.sender_type = ? AND #{Mailboxer::Message.table_name}.sender_id = ?",current_user.class.name,current_user.id)
		@offers = EquipmentEnquiry.joins(:equipment).where("equipment_enquiries.enquiry_type IN (?) AND (equipment.user_id = ? OR equipment_enquiries.user_id = ?)", [2,3], current_user.id, current_user.id).approved.order("created_at DESC")
		@proposals = current_user.buying_proposals
		@questions = EquipmentEnquiry.joins(:equipment).where("equipment_enquiries.enquiry_type = ? AND equipment.user_id = ?", 1, current_user.id).approved
		@orders = Order.all.order('created_at desc').joins(:equipment).where('equipment.user_id = ? OR orders.user_id = ? ', current_user, current_user)
		
		@received_proposals = BuyingProposal.joins(:buying_request).where('(buying_requests.user_id = ? OR buying_requests.email = ?)', current_user, current_user.email)
								
		@page_content_data = PageContentManagement.where(:page_url => "user_dashboard")
		@content_data = {}
		@page_content_data.each do |v|		
			@content_data[v.page_section] = v.content		
		end	
				
	end
	
	def ask_for_services
		@ask_for_services = StaticPage.where(:url => "ask_for_services")
	end
	
end

app/controllers/seller/equipment_enquiries_controller.rb
class Seller::EquipmentEnquiriesController < Seller::BaseController
	# Note: It seems below action not used any where, so commented it.
	# def index
	# 	@enquiries = EquipmentEnquiry.joins(:equipment).where("equipment.user_id = ?", current_user.id);
	# end
	
	def questions
		@questions = EquipmentEnquiry.joins(:equipment).where("equipment_enquiries.enquiry_type = ? AND (equipment.user_id = ? OR equipment_enquiries.user_id = ?)", 1, current_user.id, current_user.id).approved.order("created_at DESC").page(params[:page])
	end

	def offers
		#It fetches the both bids and buy requests
		@offers = EquipmentEnquiry.joins(:equipment).where("equipment_enquiries.enquiry_type IN (?) AND (equipment.user_id = ? OR equipment_enquiries.user_id = ?)", [2,3], current_user.id, current_user.id).approved.order("created_at DESC").page(params[:page])
	end

	def show_offer
		@offer = find_enquiry
		unless @offer.present?
			redirect_to seller_offers_path, notice: "Offer not found"
		end
	end

	def respond_to_offer
		@offer = find_enquiry
		
		#abort(@offer.to_json)
		#abort(@offer.equipment.to_json)
		#abort(@offer.equipment.shipping_package.to_json)
		
		#no_of_package = @offer.equipment.shipping_package.count
		
		#abort(no_of_package.to_s)
				
		if @offer.present?
			response = @offer.responses.new(user_id: current_user.id, message: enquiry_response_params[:message], attachment: enquiry_response_params[:attachment])

			if ["Confirm", "Reject"].include?(params[:commit])
				response_type = params[:commit]+"ed"  # to make it enum compatable like 'Accepted'
				if @offer.update(:response => enquiry_response_params[:message], :response_status => "Responded", :replied_as => response_type)
					response.save
					if @offer.replied_as == 'Confirmed'

						@offer.update(:enquiry_type => 3)

						order_params = [:name, :email, :mobile, :country_id, :company_website, :equipment_id].inject({}) do |params, element|
							params[element] = @offer[element]
							params
						end
						order_params[:status] = "Seller Confirmed"
						order_params[:price] = @offer.bidding_price
						order_params[:commission] = Commission.for_price(@offer.bidding_price).first.to_f
						if order_params[:commission] == 0.0
							order_params[:commission] = Commission.order("max_price DESC").first.percent.to_f
						end
						
						no_of_package = @offer.equipment.shipping_package.count
						order_params[:user_id] = @offer.user_id
						order_params[:equipment_enquiry_id] = @offer.id
						order_params[:no_of_packages] = no_of_package
						order_params[:shipping_method] = @offer.shipping_method
						order_params[:pickup_country_id] = @offer.equipment.country_id
						order_params[:pickup_city] = @offer.equipment.city
						order_params[:pickup_port] = @offer.equipment.pickup_port
						order_params[:delivery_country_id] = @offer.country_id
						order_params[:delivery_city] = @offer.delivery_city
						order_params[:delivery_port] = @offer.delivery_port
								
						order = Order.new(order_params)
						if order.save
							eq = @offer.equipment
							eq.status = 'sold'
							eq.save
							
							if no_of_package > 0								
								ShippingPackage.where(equipment_id: @offer.equipment_id).update_all(order_id: order.id)
							end
						end
					end
					flash[:notice] = "Offer #{response_type.downcase} successfully"
				else
					flash[:alert] = "Failed to process request, please try again."
				end
			else

				if @offer.update(:response => enquiry_response_params[:message])
					flash[:notice] = "Message sent successfully."
				else
					if @offer.errors.messages[:responses][0] == "is invalid"
						flash[:alert] = "Please enter maximum 2000 characters"
					end
				end
			end
			redirect_to seller_detail_inquiry_center_path(params[:id])
		else
			flash[:alert] = "Offer not found"
			redirect_to seller_inquiry_center_path
		end
		
	end

	def show_question
		@question = find_enquiry
		unless @question.present?
			redirect_to seller_questions_path, notice: "Question not found"
		end
	end

	def reply_to_question
		@question = find_enquiry
		if @question.present?
			response = @question.responses.new(user_id: current_user.id, message: enquiry_response_params[:message], attachment: enquiry_response_params[:attachment])
			if @question.update(:response => enquiry_response_params[:message], :response_status => "Responded")
					if response.save
						flash[:notice] = "Message sent successfully."
					else
						@error = response.errors.full_messages[0]
					end
			else
				if @question.errors.messages[:responses]
					@error = @question.responses.last.errors.full_messages[0]
				else
					@error = @question.errors.full_messages[0]
				end
				flash[:alert] = @error
			end
			render :action => :show_question and return if @error.present?
			redirect_to seller_detail_inquiry_center_path(params[:id])
		else
			flash[:alert] = "Inquiry not found!"
			redirect_to seller_inquiry_center_path
		end
		
	end

	def destroy
		@enquiry = find_enquiry
		if @enquiry.destroy
			flash[:notice] = "Deleted successfully"
		else
			flash[:notice] = "Failed to delete"
		end
		redirect_to :back
	end

	def unread
		@notifications = current_user.equipment_enquiries.approved.unread.limit(15)
    respond_to do |format|
      format.js
    end
  end

	private

	def find_enquiry
		enquiry = EquipmentEnquiry.approved.find_by_id params[:id]
		if current_user.present? && enquiry.present?
			enquiry.mark_as_read(current_user) unless enquiry.is_read?
		end
		enquiry
	end

	def enquiry_response_params
		params.require(:enquiry_response).permit(:message, :attachment)
	end
end

app/helpers/seller/buying_proposals_helper.rb
module Seller::BuyingProposalsHelper
	def time_diff_in_natural_language(from_time, to_time)
	  from_time = from_time.to_time if from_time.respond_to?(:to_time)
	  to_time = to_time.to_time if to_time.respond_to?(:to_time)
	  distance_in_seconds = ((to_time - from_time).abs).round
	  components = []

	  %w(year month week day).each do |interval|
	    # For each interval type, if the amount of time remaining is greater than
	    # one unit, calculate how many units fit into the remaining time.
	    if distance_in_seconds >= 1.send(interval)
	      delta = (distance_in_seconds / 1.send(interval)).floor
	      distance_in_seconds -= delta.send(interval)
	      components << pluralize(delta, interval)
	    end
	  end

	  components.join(", ")
	end
end

app/helpers/seller/buying_requests_helper.rb
module Seller::BuyingRequestsHelper
	def sent_info_request?(br)
		return BuyingRequestMoreDetail.where(buying_request_id: br.id, user_id: current_user.id).present?
	end

	def sent_proposal?(br)
		return current_user.buying_proposals.pluck(:buying_request_id).include?(br.id)
	end
end

app/helpers/seller/equipment_helper.rb
module Seller::EquipmentHelper
end

app/helpers/seller/messages_helper.rb
module Seller::MessagesHelper
end

app/views/seller/messages/_conversations.html.erb
<%= form_tag(remove_seller_messages_path, method: :post, id: 'remove_seller_messages_form')  do %>
	<!-- row -->
	<div class="row">
		<!-- Basic Table -->
		<div class="col-md-12">
			<div class="panel panel-lined panel-hovered mb20 table-responsive basic-table">
				
				<div class="panel-body">
					
					<div class="col-sm-12 col-md-12">	
						<%= link_to 'Delete','javascript:;',:class=>'btn btn-danger mr5',:id=>'delete_seller_message', style:'display:none' %>
					</div>
					
					<% if conversations.present? %>
						<table class="table">
							<thead>
								<tr>
									<th class="text-center">
										<%= check_box_tag "seller_messages_all",'all',false,:class=>"input-checkbox group_name hide-ck",:id=>"seller_messages_all" %>
									</th>
									<th></th>
									<th><%= params[:action]=='inbox' ? 'From' : 'To' %></th>
									<th>Subject</th>
									<th>Date &amp; time</th>								
								</tr>
							</thead>
							
							<tbody>
								<% conversations.each do |conversation| %>
									<tr style="<%='font-weight: bold;' unless conversation.is_read?(current_user) %>">
										<td class="text-center">
											<%= check_box_tag "seller_message_ids[]",conversation.id, false , class: "input-checkbox segment_name program_ids_active" , id: "seller_message_#{conversation.id}>" %>
										</td>
										<td>
											<%= has_attachment?(conversation) ? "<i class='fa fa-paperclip'></i>".html_safe : "&nbsp".html_safe %>
										</td>
										<td>
											<%= params[:action]=='inbox' ? last_message_from(conversation,current_user) : last_message_to(conversation,current_user) %>
										</td>
										<td><%= link_to conversation.subject, seller_message_path(conversation.id) %></td>
										<td><%= message_time_format(conversation.updated_at) %></td>
									</tr>
								<% end %>
							</tbody>
						</table>
						
						<%= paginate @conversations, :theme => 'listing_page_theme' %>
						
					<% else %>	
									
						<% if params[:action]=='inbox' %>
							<p class="no-result">No Messages Received Yet</p>
						<% else %>
							<p class="no-result">No Messages Sent Yet</p>
						<% end %>
						
					<% end %>	
					
				</div>
			</div>
		</div>
	</div>
 <% end %>

app/views/seller/messages/_unread.html.erb
<div class="tab-pane unread-msg-top">
	<div class="chat-tab tab clearfix">
		<% if conversations.present? %>
			<% conversations.each do |conversation| %>

					<% sender = conversation.receipts.sentbox.where.not("receiver_id = ? AND receiver_type = ?",current_user.id,current_user.class.name).last.try(:receiver) %>
					<%= link_to(seller_message_path(conversation)) do %>
						
						<div class="user-container mb15">
							<div class="col-md-3">
								<% if sender.try(:image).present? %>
									<%= image_tag(sender.try(:image).try(:image).try(:thumb).try(:url),class: "img-circle img-responsive", alt: "") %>
								<% else %>
									<%= image_tag("profile-noimage.jpg",class: "img-circle",alt: "") %>
								<% end %>
							</div>
							
							<div class="col-md-9">
								<p class="mb0"><%= sender.try(:name).to_s %></p>
								<p class="xsmall mb0"><%= conversation.subject %></p>
								<p class="xsmall">
									<span class="right mt5"><%= time_ago_in_words(conversation.updated_at) %></span>
									<span class="fa fa-clock-o right mr5"></span>
																		
								</p>
							</div>
							<div class="clearfix"></div>
						</div>
						
					<% end %>
					
			<% end %>
		<% else %>
			No messages
		<% end %>
	</div>
</div>

app/views/seller/messages/inbox.html.erb
<div class="page page-ui-tables page-dashboard">
	<ol class="breadcrumb breadcrumb-small">
		<li><a href="<%= seller_dashboard_path %>">Home</a></li>
		<li><a href="<%= inbox_seller_messages_path %>">Messages</a></li>
		<li class="active">Received Massages</li>	
	</ol>
	
	<div class="page-wrap">
		
		<div class="row">
			<!-- dashboard header -->
			<div class="col-md-12">
				<div class="dash-head clearfix mb20">
					<div class="left">
						<h4 class="mb5 text-light">Received Massages</h4>
					</div>
				</div>
			</div>
		</div> <!-- #end row -->
		
		<%= render partial: "conversations", locals: {conversations: @conversations} %>
		
	</div>
</div>

<%= javascript_include_tag "seller/messages" %>

app/views/seller/messages/new.html.erb
<div class="page page-ui-tables page-dashboard">
	<ol class="breadcrumb breadcrumb-small">
		<li><a href="<%= seller_dashboard_path %>">Home</a></li>
		<li class="active">Write New Message</li>	
	</ol>
	
	<div class="page-wrap">
		
		<div class="row">
			<!-- dashboard header -->
			<div class="col-md-12">
				<div class="dash-head clearfix mb20">
					<div class="left">
						<h4 class="mb5 text-light">Write New Message</h4>
					</div>
				</div>
			</div>
		</div> <!-- #end row -->
		
		<%= render 'form' %>
		
	</div>
</div>

app/views/seller/messages/sentbox.html.erb
<div class="page page-ui-tables page-dashboard">
	<ol class="breadcrumb breadcrumb-small">
		<li><a href="<%= seller_dashboard_path %>">Home</a></li>
		<li><a href="<%= sentbox_seller_messages_path %>">Messages</a></li>
		<li class="active">Sent Mail</li>	
	</ol>
	
	<div class="page-wrap">
		
		<div class="row">
			<!-- dashboard header -->
			<div class="col-md-12">
				<div class="dash-head clearfix mb20">
					<div class="left">
						<h4 class="mb5 text-light">Sent Mail</h4>
					</div>
				</div>
			</div>
		</div> <!-- #end row -->
		
		<%= render partial: "conversations", locals: {conversations: @conversations} %>
		
	</div>
</div>

<%= javascript_include_tag "seller/messages" %>

app/views/seller/messages/show.html.erb
<div class="page page-ui-tables page-dashboard">
	<ol class="breadcrumb breadcrumb-small">
		<li><a href="<%= seller_dashboard_path %>">Home</a></li>
		<li class="active">Message Detail</li>	
	</ol>
	
	<div class="page-wrap">
		
		<div class="row">
			<!-- dashboard header -->
			<div class="col-md-12">
				<div class="dash-head clearfix mb20">
					<div class="left">
						<h4 class="mb5 text-light">Message Detail</h4>
					</div>
				</div>
			</div>
		</div> <!-- #end row -->
		
<% @conversation.messages.each_with_index do |message,index| %>
	<% @message = message %>

	<% if index > 0 %>
		<div class="col-sm-12 col-md-12 mb10 text-bold">Reply Message</div>
	<% end %>
		<div class="col-sm-12 col-md-12">	
			<div class="panel panel-default panel-hovered panel-stacked mb30">
				<div class="panel-body">									
												
					<div class="form-group">
						<label class="col-md-4 control-label text-bold">From</label>
						<div class="col-md-8">
							<%= @message.receipts.try(:sentbox).try(:first).try(:receiver).try(:name) %>
						</div>
					</div>
					
					<div class="clearfix"></div>
					
					<div class="form-group mt20">
						<label class="col-md-4 control-label text-bold">To</label>
						<div class="col-md-8">
							<%= @message.receipts.try(:inbox).try(:first).try(:receiver).try(:name) %>                
						</div>
					</div>	
					
					<div class="clearfix"></div>
					
					<div class="form-group mt20">
						<label class="col-md-4 control-label text-bold">Subject</label>
						<div class="col-md-8"><%= @message.subject %></div>
					</div>
					
					<div class="clearfix"></div>
					
					<div class="form-group mt20">
						<label class="col-md-4 control-label text-bold">Message</label>
						<div class="col-md-8"><%= @message.body.to_s.html_safe  %></div>
					</div>
					
					<div class="clearfix"></div>
					
					<div class="form-group mt20">
						<label class="col-md-4 control-label text-bold">Date &amp; time</label>
						<div class="col-md-8"><%= message_time_format(@message.created_at) %></div>
					</div>
					
					<% if @message.attachment? %>
					
						<div class="clearfix"></div>
						
						<div class="form-group mt20">
							<label class="col-md-4 control-label text-bold">Attachment</label>
							<div class="col-md-8">
								<%= link_to "<i class='fa fa-paperclip'></i> #{@message.attachment.try(:url).to_s.split('/').last}".html_safe, @message.attachment.url,target: '_blank'  %>
							</div>
						</div>
	   
					<% end %> 
				
				</div>	
			</div>	
		</div>	
		<div class="clearfix"></div>

<% end %>
		
<% if @receipt.present? %>
		
	<%= form_for :message, url: reply_seller_message_path(@conversation) , :html => {id: "reply_seller_message_form", multipart: true} do |f| %>
		<% params[:message] ||= {} %>
		<%= f.hidden_field :subject, value: @message.subject %>
		<%= hidden_field_tag :message_id, @message.id %>		
		
			<div class="col-sm-12 col-md-12">	
				<div class="panel panel-default panel-hovered panel-stacked mb30">
					<div class="panel-body">									
													
						<div class="form-group">
							<label class="col-md-12 control-label text-bold mb10">Reply Message<sup>*</sup> :</label>
							<div class="col-md-12">
								<%= f.bootsy_area :body, class: 'form-control bootsy-height', id: "message" , placeholder: 'Enter Message', value: params[:message][:body], editor_options: { image: false } %>
								<%= form_error_msg_for(@receipt,'notification.body', 'Message') if @receipt.present? %>   
							</div>
						</div>
						
						<div class="clearfix"></div>
					
						<div class="form-group mt20">
							<div class="col-md-12">
								<div class="file-upload message_file">            
									<%= f.file_field :attachment %>
									<span class="label label-primary"><i class="fa fa-paperclip"></i> Attachment</span>
									<span class="max-limit">Max.32MB</span>
									<% if defined? @attachment_size %>          
										<%= "<div class='error-msg'>The attached file size is #{@attachment_size.to_f}MB but it should not exceed 32MB</div>".html_safe if @attachment_size.to_f > 32 %>
									<% end %>
								</div>
							</div>
						</div>
						
						<div class="clearfix mt20 right">
						  						   
							<button type="button" onclick="window.location = '<%= inbox_seller_messages_path %>'" class="btn btn-primary mr5">Back</button>
							<%= f.button :submit, class: "btn btn-success mr5 sent-mail-btn" do %>
							  Reply
							<% end %>
						   
						   <%= f.submit 'Submit', :class => 'submit_message_form hide' %>
						</div>
						
					</div>	
				</div>	
			</div>
		
	<% end %>
<% end %>
		
	</div>
</div>

<%= javascript_include_tag "seller/messages" %>

app/views/seller/messages/unread.js.erb
$("#unread_messages_list").html("<%= escape_javascript(render partial: 'unread', locals: { conversations: @conversations } ) %>"); 